const seeder = require("mongoose-seed");
const dotenv = require("dotenv");

const result = dotenv.config();

if (result.error) {
    // don't proceed if there was an error loading env vars
  throw result.error;
} else {
  seeder.connect(`${process.env.MONGO_URI}`, function () {
    seeder.loadModels(["./models/Product.js"]);
    seeder.clearModels(["Product"], function () {
      // Callback to populate DB once collections have been cleared
      seeder.populateModels(data, function () {
        seeder.disconnect();
      });
    });
  });
}

const data = [
  {
    model: "Product",
    documents: [
      {
        routine_step: "Hydrate",
        name: "Belif The True Cream Aqua Bomb",
        description: `An ultra-lightweight, gel-cream that instantly cools and refreshes skin while providing intensive hydration. This water-based moisturizer 'floods' the skin with a rush of refreshing hydration and minimizes the appearance of pores for soft, smooth, supple skin. Ideal for normal, combination, and oily skin types.`,
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Belif_The_True_Cream_Aqua_Bomb.png?v=1640465021",
        ingredients: [
          "water",
          "dipropylene glycol",
          "glycerin",
          "methyl trimethicone",
          "alcohol denat",
          "dimethicone",
          "cyclopentasiloxane",
          "1,2-hexanediol",
          "malakite extract",
          "caprylic/capric triglyceride",
          "pentaerythrityl tetraethylhexanoate",
          "peg/ppg/polybutylene glycol-8/5/3 glycerin",
          "alchemilla vulgaris leaf extract",
          "equisetum arvense leaf extract",
          "stellaria media (chickweed) extract",
          "urtica dioica (nettle) leaf extract",
          "plantago lanceolata leaf extract",
          "avena sativa (oat) kernel extract",
          "calendula officinalis flower extract",
          "nepeta cataria extract",
          "rubus idaeus (raspberry) leaf extract",
          "baptisia tinctoria root extract",
          "dimethiconol",
          "polymethylsilsesquioxane",
          "sodium acrylate/acryloyldimethyltaurate/dimethylacrylamide crosspolymer",
          "isohexadecane",
          "polysorbate 60",
          "ceramide 3",
          "cholesterol",
          "butyrospermum parkii (shea) butter",
          "phenl trimethicone",
          "pentaerythrityl tetraisostearate",
          "panthenol",
          "squalane",
          "triethylhexanoin",
          "macadamia ternifolia seed oil",
          "peg-150",
          "peg-40 hydrogenated castor oil",
          "acrylates/c10-30 alkyl acrylate crosspolymer",
          "c14-22 alcohols",
          "arachidyl glucoside",
          "hydrogenated lecithin",
          "peg-100 stearate",
          "stearic acid",
          "glyceryl stearate",
          "carbomer",
          "tromethamine",
          "trisodium edta",
          "fragrance",
          "citronellol",
          "limonene",
          "citral",
          "geraniol",
          "linalool",
        ],
        texture: "gel-cream",
        price_range: "$$",
        skin_type: ["normal", "dry", "combination", "oily"],
        has_fragrance: true,
        category: "moisturizer",
        has_alcohol: true,
        buy_link:
          "https://www.sephora.com/ca/en/product/the-true-cream-aqua-bomb-P394639?skuId=1686427&icid2=skugrid:p394639:product",
      },
      {
        routine_step: "Protect",
        name: "Paula's Choice RESIST Super-Light Wrinkle Defense SPF 30",
        description:
          "A lightly tinted mineral-based formula that protects skin from sun damage and fortifies it with state-of-the-art antioxidants.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Paula_s_Choice_RESIST_Super-Light_Wrinkle_Defense_SPF_30.png?v=1640465149",
        ingredients: [
          "zinc oxide (13%)",
          "water",
          "cyclopentasiloxane",
          "peg-12 dimethicone",
          "peg/​ppg-18/​18 dimethicone",
          "lauroyl lysine",
          "sodium chloride",
          "trihydroxystearin",
          "dimethicone crosspolymer",
          "resveratrol",
          "quercetin",
          "epigallocatechin gallate",
          "tocopheryl acetate",
          "tetrahexyldecyl ascorbate",
          "adenosine",
          "bisabolol",
          "salix alba (willow) bark extract",
          "punica granatum (pomegranate) extract",
          "haematococcus pluvialis extract",
          "hydrolyzed corn starch",
          "polysorbate 80",
          "hydrated silica",
          "triethoxycaprylylsilane",
          "c12-15 alkyl benzoate",
          "isopropyl titanium triisostearate",
          "caprylyl glycol",
          "hexylene glycol",
          "ethylhexylglycerin",
          "iron oxide ci77491",
          "iron oxide ci 77492",
          "iron oxide ci 77499",
          "phenoxyethanol",
        ],
        texture: "lotion",
        price_range: "$$",
        skin_type: ["normal", "oily", "combination"],
        has_fragrance: false,
        spf: 50,
        is_waterproof: false,
        sunscreen_type: ["physical"],
        category: "sunscreen",
        has_alcohol: false,
        buy_link:
          "https://www.paulaschoice.com/resist-super-light-wrinkle-defense-spf-30/776.html",
      },
      {
        routine_step: "Hydrate & Protect",
        name: "Paula's Choice RESIST Skin Restoring Moisturizer with SPF 50",
        description: `This antioxidant-rich moisturizer hydrates and protects with superstar ingredients like niacinamide, shea butter and licorice for flawless, younger-looking skin.`,
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Paula_s_Choice_RESIST_Skin_Restoring_Moisturizer_with_SPF_50.png?v=1640465695",
        ingredients: [
          "avobenzone (3%)",
          "homosalate (5%)",
          "octinoxate (7.50%)",
          "octisalate (5%)",
          "oxybenzone (5%)",
          "water (aqua)",
          "silica",
          "glycerin",
          "cetearyl alcohol",
          "dimethicone",
          "butylene glycol",
          "pentylene glycol",
          "potassium cetyl phosphate",
          "cyclopentasiloxane",
          "pyrus malus (apple) fruit extract",
          "vp/​eicosene copolymer",
          "butyrospermum parkii (shea) butter",
          "allantoin",
          "niacinamide",
          "tocopherol",
          "glycyrrhiza glabra (licorice) root extract",
          "aloe barbadensis leaf juice",
          "atractylodes macrocephala root powder",
          "avena sativa (oat) kernel extract",
          "coffea arabica (coffee) seed extract",
          "portulaca oleracea extract",
          "mahonia aquifolium root extract",
          "diethylhexyl syringylidenemalonate",
          "sarcosine",
          "capryloyl glycine",
          "maltooligosyl glucoside",
          "cetearyl glucoside",
          "dimethiconol",
          "acrylates/​c10-30 alkyl acrylate crosspolymer",
          "hydrogenated starch hydrolysate",
          "hexylene glycol",
          "4-t-butylcyclohexanol",
          "glyceryl stearate",
          "peg-100 stearate",
          "sodium hydroxide",
          "xanthan gum",
          "disodium edta",
          "phenoxyethanol",
          "caprylyl glycol (preservatives)",
          "ethylhexylglycerin",
        ],
        texture: "cream",
        price_range: "$$",
        skin_type: ["normal", "dry"],
        has_fragrance: false,
        spf: 50,
        is_waterproof: false,
        sunscreen_type: ["chemical"],
        category: "moisturizer",
        has_alcohol: false,
        buy_link:
          "https://www.paulaschoice.com/resist-skin-restoring-moisturizer-with-spf-50/797.html",
      },
      {
        routine_step: "Hydrate",
        name: "Olay Regenerist Micro-Sculpting Cream Fragrance Free",
        description: `“The Red Jar” – known to many as their go-to, nonnegotiable face moisturizer with over 1 billion jars sold, Olay Micro-Sculpting Fragrance-Free Face Cream is designed to start visibly reducing wrinkles & fine lines starting day 1. Infused with Vitamin B3, Amino-Peptides, Hyaluronic Acid and Antioxidants for ultimate penetration, this moisture-binding moisturizing formula instantly hydrates to visibly firm skin for a lifted look."`,
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Olay_Regenerist_Micro-Sculpting_Cream_Fragrance_Free.png?v=1640467957",
        ingredients: [
          "water",
          "glycerin",
          "isohexadecane",
          "niacinamide",
          "isopropyl isostearate",
          "aluminum starch octenylsuccinate",
          "nylon-12",
          "dimethicone",
          "panthenol",
          "tocopheryl acetate",
          "palmitoyl pentapeptide-4",
          "sodium peg-7 olive oil carboxylate",
          "sodium hyaluronate",
          "caprylic/capric triglyceride",
          "ceratonia siliqua (carob) fruit extract",
          "stearyl alcohol",
          "polyethylene",
          "cetyl alcohol",
          "behenyl alcohol",
          "sodium acrylates copolymer",
          "titanium dioxide",
          "benzyl alcohol",
          "methylparaben",
          "ethylparaben",
          "dimethiconol",
          "polyacrylamide",
          "peg-100 stearate",
          "propylparaben",
          "cetearyl glucoside",
          "cetearyl alcohol",
          "c13-14 isoparaffin",
          "disodium edta",
          "citric acid",
          "stearic acid",
          "palmitic acid",
          "c12-13 pareth-3",
          "laureth-7",
          "sodium hydroxide",
          "mica",
        ],
        texture: "cream",
        price_range: "$$",
        skin_type: ["mature"],
        has_fragrance: false,
        category: "moisturizer",
        has_alcohol: false,
        buy_link:
          "https://www.walmart.ca/en/ip/olay-regenerist-advanced-anti-aging-micro-sculpting-cream/6000045963143?cmpid=AF_CA_1680615_1&utm_source=rakuten&utm_medium=affiliate&utm_campaign=always_on&utm_content=10&utm_id=AF_CA_1680615_1&siteID=jo_pTdthTuc-JO9Qay2OG_aoM7KKsTQBnQ&wmlspartner=jo%2FpTdthTuc",
      },
      {
        routine_step: "Hydrate",
        name: "Tatcha The Water Cream Oil-Free Pore Minimizing Moisturizer",
        description:
          "This lightweight, clarifying water cream releases a burst of hydrating nutrients and pore-refining botanicals for healthy aging and smooth, balanced skin.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Tatcha_The_Water_Cream_Oil-Free_Pore_Minimizing_Moisturizer.png?v=1640465873",
        ingredients: [
          "water",
          "saccharomyces/camellia sinensis leaf/cladosiphon okamuranus/rice ferment filtrate*",
          "dimethicone",
          "propanediol",
          "glycerin",
          "diglycerin",
          "diphenylsiloxy phenyl trimethicone",
          "gold",
          "belamcanda chinensis root extract",
          "rosa multiflora fruit extract",
          "houttuynia cordata extract",
          "sophora angustifolia root extract",
          "sodium hyaluronate",
          "lecithin",
          "pistacia lentiscus (mastic) gum",
          "sodium chloride",
          "sodium citrate",
          "mica",
          "peg-9 polydimethylsiloxyethyl dimethicone",
          "dimethicone/peg-10/15 crosspolymer",
          "dimethicone/phenyl vinyl dimethicone crosspolymer",
          "disodium edta",
          "tin oxide",
          "titanium dioxide",
          "butylene glycol",
          "ethylhexylglycerin",
          "parfum/fragrance",
          "alcohol",
          "phenoxyethanol",
          "hadasei-3",
        ],
        texture: "gel-cream",
        price_range: "$$$",
        skin_type: ["normal", "oily", "combination"],
        has_fragrance: true,
        category: "moisturizer",
        has_alcohol: true,
        is_clean: true,
        buy_link:
          "https://www.sephora.com/ca/en/product/the-water-cream-P418218?skuId=1932920&icid2=skugrid:p418218:product",
      },
      {
        routine_step: "Hydrate",
        name: "Neutrogena Hydro Boost Facial Gel Cream Extra Dry Skin",
        description:
          "Neutrogena Hydro Boost Gel Cream Extra-Dry instantly quenches dry skin and keeps it looking smooth, supple and hydrated all day. Our unique light-weight formula absorbs quickly, like a gel, but has the long-lasting, intense moisturizing power of a cream, for even extra dry skin. It boosts skin's hydration level and locks it in all day. Formulated with hydrating hyaluronic acid, naturally found in skin, it acts as a sponge for dry skin cells, resulting in more supple and smooth skin.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Neutrogena_Hydro_Boost_Facial_Gel_Cream_Extra_Dry_Skin.png?v=1640465954",
        ingredients: [
          "water (eau)",
          "dimethicone",
          "glycerin",
          "cetearyl olivate",
          "polyacrylamide",
          "sorbitan olivate",
          "phenoxyethanol",
          "dimethicone/vinyl dimethicone crosspolymer",
          "synthetic beeswax",
          "c13-14 isoparaf¬fin,dimethicone crosspolymer",
          "dimethiconol",
          "chlorphenesin",
          "carbomer",
          "laureth-7",
          "sodium hyaluronate",
          "ethylhexylglycerin",
          "c12-14 pareth-12",
          "sodium hydroxide",
        ],
        texture: "gel-cream",
        price_range: "$",
        skin_type: ["all"],
        has_fragrance: false,
        category: "moisturizer",
        has_alcohol: false,
        buy_link:
          "https://www.walmart.ca/en/ip/neutrogena-hydro-boost-facial-gel-cream-for-extra-dry-skin-hyaluronic-acid-to-hydrate-skin-gel-moisturizer-47ml/6000192034941",
      },
      {
        routine_step: "Hydrate & Protect",
        name: "EltaMD UV Daily Broad-Spectrum SPF 40",
        description: `Serious UV protection and superior hydration join forces in this sheer facial sunscreen. EltaMD UV Daily has hyaluronic acid to boost moisture retention and diminish fine lines. This lightweight moisturizer with UV protection can be worn alone or under makeup. Choose from tinted and untinted formulas for use every day.`,
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/EltaMD_UV_Daily_Broad-Spectrum_SPF_40.png?v=1640466025",
        ingredients: [
          "zinc oxide (9%)",
          "octinoxate (7.5%)",
          "purified water",
          "petrolatum",
          "isopropyl palmitate",
          "cetearyl glucoside",
          "dimethicone",
          "hydroxyethyl acrylate",
          "sodium acryloyldimethyl taurate copolymer",
          "polisobutene",
          "peg-7 trimethylolpropane coconut ether",
          "sodium hyaluronate",
          "tocopheryl acetate",
          "polyether-1",
          "citric acid",
          "oleth-3 phosphate",
          "phenoxyethanol",
          "butylene glycol",
          "iodopropynyl butylcarbamate",
          "triethoxycaprylylsilane",
        ],
        texture: "lotion",
        price_range: "$$$",
        skin_type: ["normal", "combination", "sensitive"],
        has_fragrance: false,
        spf: 40,
        is_waterproof: false,
        sunscreen_type: ["physical", "chemical"],
        category: "moisturizer",
        has_alcohol: false,
        buy_link:
          "https://www.amazon.ca/Eltamd-Daily-SPF-48-Gram-1-7-Ounce/dp/B00464EC1E/ref=sr_1_2?crid=1LAOSWJEITPF6&keywords=EltaMD+UV+Daily+Broad-Spectrum+SPF+40&qid=1640468256&s=beauty&sprefix=eltamd+uv+daily+broad-spectrum+spf+40%2Cbeauty%2C103&sr=1-2",
      },
      {
        routine_step: "Hydrate & Protect",
        name: "Peter Thomas Roth Water Drench Broad Spectrum SPF 45 Hyaluronic Cloud Moisturizer",
        description:
          "Drench your skin with a liquid cloud of fluffy-light moisture that feels soft and weightless like clouds in the atmosphere, shielding against UVA/UVB rays while helping to keep skin hydrated during sun exposure with a 30% Hyaluronic Acid Complex. Non-greasy, cream-to-water invisible broad-spectrum SPF 45 sunscreen has a 30% complex of Hyaluronic Acid, a potent hydrator that draws in water. Helps plump the look of skin with moisture.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Peter_Thomas_Roth_Water_Drench_Broad_Spectrum_SPF_45_Hyaluronic_Cloud_Moisturizer.png?v=1640466145",
        ingredients: [
          "octocrylene (10%)",
          "octisalate (5%)",
          "homosalate (5%)",
          "avobenzone (3%)",
          "water/aqua/eau",
          "polymethylsilsesquioxane",
          "glycerin",
          "dipropylene glycol",
          "dimethicone",
          "argania spinosa kernel oil",
          "dl-alpha tocopheryl acetate",
          "yeast extract",
          "cyclopentasiloxane",
          "cyclohex- asiloxane",
          "phenoxyethanol",
          "lauryl peg-9 polydimethylsiloxyethyl dimethicone,isododecane",
          "dimethicone/peg-10/15 crosspolymer",
          "saccharide isomerate",
          "methyl gluceth-20",
          "sodium chloride",
          "sodium hyaluronate",
          "bisabolol",
          "peg-15/ lauryl dimethicone crosspolymer",
          "sodium pca",
          "propylene glycol",
          "ceteareth-25",
          "sodium benzoate",
          "potassium sorbate",
          "sodium citrate",
          "citric acid",
          "sambucus nigra fruit extract",
          "cetyl alcohol",
          "saccharomyces/magnesium ferment",
          "hydrolyzed silk",
          "behenic acid",
          "ceramide np",
          "cholesterol",
          "ethylhexylglycerin",
          "mica (ci 77019)",
          "deltatocopherol",
          "cera- mide ns",
          "saccharomyces/iron ferment",
          "saccharomyces/copper ferment",
          "saccharomyces/silicon ferment",
          "saccharo- myces/zinc ferment",
          "butylene glycol,ceramide ap",
          "ceramide eop",
          "ceramide eos",
          "olea europaea (olive) leaf extract",
          "caprooyl phytosphingosine",
          "caprooyl sphingosine",
          "disodium edta",
          "ascorbyl palmitate",
        ],
        texture: "gel-cream",
        price_range: "$$$",
        skin_type: ["all"],
        has_fragrance: false,
        spf: 45,
        is_waterproof: true,
        sunscreen_type: ["chemical"],
        category: "moisturizer",
        has_alcohol: false,
        buy_link:
          "https://www.sephora.com/ca/en/product/peter-thomas-roth-water-drench-reg-broad-spectrum-spf-45-hyaluronic-cloud-moisturizer-P472822?skuId=2450468&keyword=Peter%20Thomas%20Roth%20Water%20Drench%20Broad%20Spectrum%20SPF%2045%20Hyaluronic%20Cloud",
      },
      {
        routine_step: "Protect",
        name: "EltaMD UV Clear Broad-Spectrum SPF 46",
        description:
          "Oil-free EltaMD UV Clear helps calm and protect sensitive skin types prone to discoloration and breakouts associated to acne and rosacea. It contains niacinamide (vitamin B3), hyaluronic acid and lactic acid, ingredients that promote the appearance of healthy-looking skin. Very lightweight and silky, it may be worn with makeup or alone. Choose from tinted and untinted formulas for use every day.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/EltaMD_UV_Clear_Broad-Spectrum_SPF_46.png?v=1640466222",
        ingredients: [
          "zinc oxide (9%)",
          "octinoxate (7.5%)",
          "purified water",
          "cyclomethicone",
          "niacinamide",
          "octyldodecyl neopentanoate",
          "hydroxyethyl acrylate/sodium acryloyldimethyl taurate copolymer",
          "polyisobutene",
          "peg-7 trimethylolpropane coconut ether",
          "sodium hyaluronate",
          "tocopheryl acetate",
          "lactic acid",
          "oleth-3 phosphate",
          "phenoxyethanol",
          "butylene glycol",
          "iodopropynyl butylcarbamate",
          "triethoxycaprylylsilane",
        ],
        texture: "lotion",
        price_range: "$$$",
        skin_type: ["acne-prone", "hyperpigmentation", "rosacea", "sensitive"],
        has_fragrance: false,
        spf: 46,
        is_waterproof: false,
        sunscreen_type: ["physical", "chemical"],
        category: "sunscreen",
        has_alcohol: false,
        buy_link:
          "https://www.amazon.ca/Eltamd-Clear-SPF-48-Gram-1-7/dp/B002MSN3QQ",
      },
      {
        routine_step: "Protect",
        name: "Supergoop! Unseen Sunscreen SPF 40 PA+++",
        description:
          "The original, totally invisible, weightless, scentless sunscreen with SPF 40 that leaves a velvety finish. This innovative, antioxidant-rich multitasker has a unique oil-free formula that glides onto skin while providing broad spectrum SPF 40 protection. Use it as a makeup-gripping primer under foundation when you want a little more coverage, or on its own if you want a more natural look. It’s a totally game-changing way to wear sunscreen every day, and it will have you SPF-Obsessed™.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Supergoop_Unseen_Sunscreen_SPF_40_PA.png?v=1640466286",
        ingredients: [
          "avobenzone (3%)",
          "homosalate (8%)",
          "octisalate (5%)",
          "octocrylene (4%)",
          "isododecane",
          "dimethicone crosspolymer",
          "dimethicone/bis-isobutyl ppg-20 crosspolymer",
          "polymethylsilsesquioxane",
          "isohexadecane",
          "dicaprylyl carbonate",
          "meadowfoam estolide",
          "caprylic/capric triglyceride",
          "polyester-7",
          "neopentyl glycol diheptanoate",
          "lithothamnion calcareum extract",
          "caprylyl glycol",
          "butyrospermum parkii (shea) butter",
          "jojoba esters",
          "mannitol",
          "olibanum",
          "lecithin",
          "microcrystalline cellulose",
          "diatomaceous earth",
          "zinc sulfate",
          "silica",
          "tocopherol",
        ],
        texture: "gel",
        price_range: "$$$",
        skin_type: ["all"],
        has_fragrance: false,
        spf: 40,
        is_waterproof: true,
        sunscreen_type: ["chemical"],
        category: "sunscreen",
        has_alcohol: false,
        is_clean: true,
        buy_link:
          "https://www.sephora.com/ca/en/product/supergoop-unseen-sunscreen-P458907?skuId=2354207&icid2=skugrid:p458907:product",
      },
      {
        routine_step: "Protect",
        name: "Biore UV Aqua Rich Watery Essence SPF 50 PA++++",
        description: `Biore UV Aqua Rich Watery Essence has a light-weight feeling yet it effectively protects from strong UV rays, preventing aging skin and sunburn. This Japanese sunscreen features UV blocking ingredients such as water capsules which when applied to the skin create a pleasant, watery veil. The new formula is enhanced with the so called "Micro Defense" technology which prevents the formation of micro gaps and potential uneven coating. It also contains moisturizing ingredients such as hyaluronic acid, royal jelly and citrus essence to retain moisture.`,
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Biore_UV_Aqua_Rich_Watery_Essence_SPF_50_PA.png?v=1640466521",
        ingredients: [
          "water",
          "alcohol",
          "ethylhexyl methoxycinnamate",
          "ethylhexyl triazone",
          "isopropyl palmitate",
          "lauryl methacrylate/​sodium methacrylate crosspolymer",
          "diethylamino hydroxybenzoyl hexyl benzoate",
          "hydrogenated polyisobutene",
          "bis-ethylhexyloxyphenol methoxyphenyl triazine",
          "dextrin palmitate",
          "butylene glycol",
          "xylitol",
          "acrylates/​c10-30 alkyl acrylate crosspolymer",
          "dimethicone",
          "c12-15 alkyl benzoate",
          "glycerin",
          "glyceryl stearate",
          "propanediol",
          "glyceryl behenate",
          "vinyl dimethicone/​methicone silsesquioxane crosspolymer",
          "cetyl alcohol",
          "agar",
          "sorbitan distearate",
          "isoceteth-20",
          "polyvinyl alcohol",
          "dimethicone/​vinyl dimethicone crosspolymer",
          "stearoyl glutamic acid",
          "arginine",
          "potassium hydroxide",
          "sodium hydroxide",
          "royal jelly extract",
          "sodium hyaluronate",
          "phenoxyethanol",
          "disodium edta",
          "bht",
          "fragrance",
        ],
        texture: "essence",
        price_range: "$",
        skin_type: ["normal", "oily", "combination"],
        has_fragrance: true,
        spf: 50,
        is_waterproof: true,
        sunscreen_type: ["chemical"],
        category: "sunscreen",
        has_alcohol: true,
        buy_link:
          "https://www.stylevana.com/en_CA/kao-biore-uv-aqua-rich-watery-essence-spf-50-pa-2019-edition.html",
      },
      {
        routine_step: "Cleanse",
        name: "Neutrogena Ultra Gentle Hydrating Cleanser",
        description:
          "Thoroughly cleanse and leave your skin feeling moisturized for naturally soft skin with NEUTROGENA® Ultra Gentle Daily Cleanser, Creamy Formula. This creamy cleanser works in an advanced, skin-friendly way. Uniquely formulated with minimal ingredients, this effective cleanser gently removes excess oil, dirt and makeup. NEUTROGENA® Ultra Gentle Daily Cleanser, Creamy Formula is hypoallergenic, non-comedogenic, fragrance-free, paraben-free, soap-free and dye-free.",
        ingredients: [
          "water",
          "glycerin",
          "cetearyl alcohol",
          "polyglyceryl-10 laurate",
          "phenoxyethanol",
          "cetearyl glucoside",
          "caprylyl glycol",
          "carbomer",
          "sodium hydroxide",
          "ethylhexylglycerin",
        ],
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Neutrogena_Ultra_Gentle_Hydrating_Cleanser.png?v=1640466705",
        texture: "creamy",
        price_range: "$",
        skin_type: ["dry", "sensitive"],
        has_fragrance: false,
        removes_makeup: false,
        category: "cleanser",
        buy_link:
          "https://www.walmart.ca/en/ip/neutrogena-ultra-gentle-daily-creamy-facial-cleanser-fragrance-free/676118",
      },
      {
        routine_step: "Cleanse",
        name: "CeraVe Foaming Facial Cleanser",
        description:
          "Developed with dermatologists, CeraVe Foaming Cleanser's gently foams to deeply cleanse without disrupting the natural skin protective barrier. This refreshing gel, with 3 essential ceramides and hyaluronic acid, effectively removes excess oil, dirt, and makeup.",
        ingredients: [
          "aqua/water/eau",
          "cocamidopropyl hydroxysultaine",
          "glycerin",
          "sodium lauroyl sarcosinate",
          "peg-150 pentaerythrityl tetrastearate",
          "niacinamide",
          "peg-6 caprylic/capric glycerides",
          "sodium methyl cocoyl taurate",
          "propylene glycol",
          "ceramide np",
          "ceramide ap",
          "ceramide eop",
          "carbomer",
          "methylparaben",
          "sodium chloride",
          "sodium lauroyl lactylate",
          "cholesterol",
          "disodium edta",
          "propylparaben",
          "citric acid",
          "tetrasodium edta",
          "hydrolyzed hyaluronic acid",
          "phytosphingosine",
          "xanthan gum",
        ],
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/CeraVe_Foaming_Facial_Cleanser.png?v=1640466769",
        texture: "gel",
        price_range: "$",
        skin_type: ["normal", "oily", "combination"],
        has_fragrance: false,
        removes_makeup: false,
        category: "cleanser",
        buy_link:
          "https://www.walmart.ca/en/ip/cerave-foaming-facial-cleanser-with-hyaluronic-acid-and-3-ceramides-daily-face-wash-for-normal-to-oily-skin-fragrance-free/6000200706456",
      },
      {
        routine_step: "Cleanse",
        name: "CeraVe Hydrating Cleanser",
        description:
          "Developed with dermatologists, CeraVe Hydrating Cleanser, effectively cleanses and hydrates without disrupting the natural skin protective barrier. This non-foaming lotion, with 3 essential ceramides and hyaluronic acid, gently removes dirt and oil while increasing skin hydration after just one use.",
        ingredients: [
          "aqua",
          "glycerin",
          "cetearyl alcohol",
          "ceramide np",
          "ceramide ap",
          "ceramide eop",
          "phytosphingosine",
          "cholesterol",
          "hyaluronic acid",
          "sodium lauroyl lactylate",
          "behentrimonium methosulfate",
          "glyceryl monostearate",
          "stearyl alcohol",
          "cetyl alcohol",
          "peg-40 stearate",
          "polysorbate 20",
          "potassium phosphate",
          "dipotassium phosphate",
          "methylparaben",
          "propylparaben",
          "disodium edta",
          "carbomer",
          "xanthan gum",
        ],
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/CeraVe_Hydrating_Cleanser.png?v=1640502537",
        texture: "lotion",
        price_range: "$",
        skin_type: ["normal", "dry", "combination"],
        has_fragrance: false,
        removes_makeup: false,
        category: "cleanser",
        buy_link:
          "https://www.walmart.ca/en/ip/cerave-hydrating-facial-cleanser-with-hyaluronic-acid-and-3-ceramides-daily-face-wash-for-normal-to-dry-skin-fragrance-free/6000200706742",
      },
      {
        routine_step: "Cleanse",
        name: "COSRX Low pH Good Morning Gel Cleanser",
        description: `A super gentle cleanser that's great for your morning wash this low pH formula gel cleanser doesn't strip your skin of its natural oils and contains purifying botanical ingredients and mild acids to gently cleanse your skin to its most supple and clear texture`,
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/COSRX_Low_pH_Good_Morning_Gel_Cleanser.png?v=1640466864",
        ingredients: [
          "water",
          "cocamidopropyl betaine",
          "sodium lauroyl methyl isethionate",
          "polysorbate 20",
          "styrax japonicus branch/​fruit/​leaf extract",
          "butylene glycol",
          "saccharomyces ferment",
          "cryptomeria japonica leaf extract",
          "nelumbo nucifera leaf extract",
          "pinus palustris leaf extract",
          "ulmus davidiana root extract",
          "evening primrose flower extract",
          "pueraria lobata root extract",
          "tea tree leaf oil",
          "allantoin",
          "caprylyl glycol",
          "ethylhexylglycerin",
          "betaine salicylate",
          "citric acid",
          "ethyl hexanediol",
          "1,2-hexanediol",
          "trisodium ethylenediamine disuccinate",
          "sodium benzoate",
          "disodium edta",
        ],
        texture: "gel",
        price_range: "$",
        skin_type: ["all"],
        has_fragrance: true,
        removes_makeup: false,
        category: "cleanser",
        buy_link:
          "https://www.stylevana.com/en_US/cosrx-low-ph-good-morning-gel-cleanser-150ml-8.html",
      },
      {
        routine_step: "Remove",
        name: "Bioderma Sensibio H2O Micellar Water",
        description:
          "This micelle solution is a soothing non-rinse cleanser and make-up remover. The perfectly cleanses and removes make-up from the face and eyes. Soothes irritated skin and minimises redness.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Bioderma_Sensibio_H2O_Micellar_Water.png?v=1640466946s",
        ingredients: [
          "water (aqua)",
          "peg-6 caprylic/capric glycerides",
          "cucumis sativus (cucumber) fruit extract",
          "mannitol",
          "xylitol",
          "rhamnose",
          "fructooligosaccharides",
          "propylene glycol",
          "disodium edta",
          "cetrimonium bromide",
        ],
        texture: "water",
        price_range: "$$",
        skin_type: ["all", "sensitive"],
        has_fragrance: false,
        has_alcohol: false,
        removes_makeup: true,
        category: "makeup_remover",
        buy_link:
          "https://shop.shoppersdrugmart.ca/Luxury/Brands/Bioderma/Sensibio-H2O-Micelle-Solution/p/BI92",
      },
      {
        routine_step: "Remove",
        name: "Clinique Take The Day Off Cleansing Balm Makeup Remover",
        description:
          "A gentle, effective makeup remover that transforms from a balm to a silky oil, melting away face and eye makeup and sunscreen.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/CLINIQUE_Take_The_Day_Off_Cleansing_Balm_Makeup_Remover.png?v=1640467037",
        ingredients: [
          "ethylhexyl palmitate",
          "carthamus tinctorius (safflower) seed oil",
          "caprylic/capric triglyceride",
          "sorbeth-30 tetraoleate",
          "polyethylene",
          "peg-5 glyceryl triisostearate",
          "water",
          "tocopherol",
          "phenoxyethanol",
        ],
        texture: "balm",
        price_range: "$$$",
        skin_type: ["normal", "dry", "combination", "oily"],
        has_fragrance: false,
        has_alcohol: false,
        removes_makeup: true,
        category: "makeup_remover",
        is_clean: true,
        buy_link:
          "https://www.sephora.com/ca/en/product/take-the-day-off-cleansing-balm-P126301?skuId=886267&icid2=skugrid:p126301:product",
      },
      {
        routine_step: "Remove",
        name: "Neutrogena All-in-One Makeup Removing Cleansing Wipes",
        description:
          "NEUTROGENA® All-in-One Make-Up Removing Cleansing Wipes are soft, pre-moistened wipes, infused with a mild cleansing lotion. They not only gently and effectively cleanse and remove all types of make-up but also tone skin, leaving it refreshed in just one convenient step. Skin conditioning ingredients help prevent over-drying and leave your skin feeling soft and looking healthy. Gentle enough to use around sensitive eye area, even for contact lens wearers.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Neutrogena_All-in-One_Makeup_Removing_Cleansing_Wipes.png?v=1640467119",
        ingredients: [
          "water (eau)",
          "cetyl ethylhexanoate",
          "isostearyl palmitate",
          "pentaerythrityl tetraethylhexanoate",
          "isononyl isononanoate",
          "cyclopentasiloxane",
          "hexylene glycol",
          "peg-4 laurate",
          "peg-6 caprylic/capric glycerides",
          "sucrose cocoate",
          "carbomer",
          "sodium hydroxide",
          "benzoic acid",
          "dehydroacetic acid",
          "phenoxyethanol",
          "iodopropynyl butylcarbamate",
          "parfum",
        ],
        texture: "wipes",
        price_range: "$",
        skin_type: ["all"],
        has_fragrance: true,
        has_alcohol: false,
        removes_makeup: true,
        category: "makeup_remover",
        buy_link:
          "https://www.walmart.ca/en/ip/neutrogena-makeup-removing-wipes-all-in-one/6000075838885",
      },
      {
        routine_step: "Remove",
        name: "Garnier SkinActive Micellar Cleansing Water All-in-1 Sensitive Skin",
        description:
          "Cleanse with care with Garnier SkinActive Micellar Cleansing Water. Micellar cleansing water is a facial cleanser and makeup remover that is surprisingly powerful, yet gentle on skin. Garnier micellar water all-in-1 effectively cleanses, removes makeup and refreshes skin in one easy step. Like a magnet, micelles capture and lift away dirt, oil and makeup without harsh rubbing. It can be used to remove all traces of makeup, including waterproof eyeliners and longwear lipstick, dissolving all traces of makeup, dirt and oil. The mild formula is safe for all skin types, dermatologist-tested and free from parabens, sulfates, silicone and fragrance.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Garnier_SkinActive_Micellar_Cleansing_Water_All-in-1_Sensitive_Skin.png?v=1640467190",
        ingredients: [
          "aqua",
          "hexylene glycol",
          "glycerin",
          "bht",
          "disodium cocoamphodiacetate",
          "disodium edta",
          "poloxamer 184",
          "polyaminopropyl biguanidee",
        ],
        texture: "water",
        price_range: "$",
        skin_type: ["all", "sensitive"],
        has_fragrance: false,
        has_alcohol: false,
        removes_makeup: true,
        category: "makeup_remover",
        buy_link:
          "https://www.walmart.ca/en/ip/garnier-skinactive-all-in-1-micellar-cleansing-water-for-all-skin-types-even-sensitive-700-ml/6000203946698",
      },
      {
        routine_step: "Remove",
        name: "Farmacy Green Clean Makeup Removing Cleansing Balm",
        description:
          "An award-winning makeup-removing face cleanser that melts away stubborn makeup, SPF, dirt, and oil and leaves skin hydrated with zero residue",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Farmacy_Green_Clean_Makeup_Removing_Cleansing_Balm.png?v=1640467266",
        ingredients: [
          "caprylic/capric triglyceride",
          "peg-20 glyceryl triisostearate",
          "peg-10 isostearate",
          "polyethylene",
          "echinacea purpurea root extract",
          "carica papaya (papaya) fruit extract",
          "moringa pterygosperma seed extract",
          "moringa oleifera seed oil",
          "zingiber officinale (ginger) root oil",
          "helianthus annuus (sunflower) seed oil",
          "sorbitan sesquioleate",
          "citrus aurantifolia (lime) oil",
          "citrus aurantium bergamia (bergamot) fruit oil",
          "glycerin",
          "melia azadirachta leaf extract",
          "melia azadirachta flower extract",
          "corallina officinalis extract",
          "citrus aurantium dulcis (orange) peel oil",
          "amber powder",
          "cananga odorata flower oil",
          "coccinia indica fruit extract",
          "solanum melongena (eggplant) fruit extract",
          "curcuma longa (turmeric) root extract",
          "ocimum sanctum leaf extract",
          "water",
          "butylene glycol",
          "disodium phosphate",
          "citric acid",
          "phenoxyethanol",
          "citral",
          "limonene",
          "linalool",
        ],
        texture: "balm",
        price_range: "$$",
        skin_type: ["normal", "dry", "combination", "oily"],
        has_fragrance: true,
        has_alcohol: false,
        removes_makeup: true,
        category: "makeup_remover",
        is_clean: true,
        buy_link:
          "https://www.sephora.com/ca/en/product/green-clean-makeup-meltaway-cleansing-balm-P417238?skuId=1899103&icid2=skugrid:p417238:product",
      },
      {
        routine_step: "Remove",
        name: "Farmacy Clearly Clean Makeup Removing Cleansing Balm",
        description:
          "A fragrance-free, PEG-free makeup removing cleansing balm that melts away stubborn eye and long-wear makeup, SPF, and dirt—made for sensitive and reactive skin.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Farmacy_Clearly_Clean_Makeup_Removing_Cleansing_Balm.png?v=1640467347",
        ingredients: [
          "cetyl ethylhexanoate",
          "synthetic wax",
          "coco-caprylate/caprate",
          "caprylic/capric triglyceride",
          "polyglyceryl-10 dioleate",
          "polyglyceryl-6 dicaprate",
          "sorbitan oleate decylglucoside crosspolymer",
          "helianthus annuus (sunflower) seed oil",
          "moringa oleifera seed extract",
          "carica papaya (papaya) fruit extract",
          "moringa oleifera leaf water",
          "pentylene glycol",
          "gluconolactone",
          "polyglyceryl-6 oleate",
          "glyceryl citrate/lactate/linoleate/oleate",
          "sorbitan sesquioleate",
          "potassium olivate",
          "glyceryl caprylate",
          "polyglyceryl-3 caprate",
          "polyglyceryl-4 cocoate",
          "sodium chloride",
          "butylene glycol",
          "water/aqua/eau",
          "sodium benzoate",
          "maltodextrin",
          "glyceryl laurate",
        ],
        texture: "balm",
        price_range: "$$",
        skin_type: ["all"],
        has_fragrance: false,
        has_alcohol: false,
        removes_makeup: true,
        category: "makeup_remover",
        is_clean: true,
        buy_link:
          "https://www.sephora.com/ca/en/product/farmacy-clearly-clean-cleansing-balm-P477157?skuId=2501229&keyword=Farmacy%20Clearly%20Clean%20Makeup%20Removing%20Cleansing%20Balm",
      },
      {
        routine_step: "Cleanse",
        name: "Sukin Sensitive Cleansing Gel",
        description:
          "Our soap free Sensitive Cleansing Gel provides a gentle, non-drying cleanse to help remove impurities and excess oils. A blend of Green Tea, Cucumber and Avocado Oil work to gently clean, refresh and purify, leaving skin feeling soft, clear and balanced. This is the perfect cleansing option for combination/oily skin types who have sensitive skin.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Sukin_Sensitive_Cleansing_Gel.png?v=1640464425",
        ingredients: [
          "water (aqua)",
          "aloe barbadensis leaf juice",
          "cocamidopropyl betaine",
          "decyl glucoside",
          "peg-150 pentaerythrityl tetrastearate",
          "cucumis sativus (cucumber) fruit extract",
          "chamomilla recutita (matricaria) flower extract (chamomile)",
          "camellia sinensis (green tea) leaf extract",
          "persea gratissima (avocado) oil",
          "rosa canina fruit oil (rosehip)",
          "glycerin",
          "vanillin",
          "vanilla planifolia fruit extract",
          "phenoxyethanol",
          "benzyl alcohol",
        ],
        texture: "gel",
        price_range: "$",
        skin_type: ["oily", "combination", "sensitive"],
        has_fragrance: true,
        has_alcohol: false,
        category: "cleanser",
        is_clean: true,
        buy_link:
          "https://shop.shoppersdrugmart.ca/Luxury/Sukin/Sensitive-Cleansing-Gel/p/LD1778",
      },
      {
        routine_step: "Hydrate",
        name: "Sukin Sensitive Facial Moisturizer",
        description:
          "Our fast-absorbing Sensitive Facial Moisturiser helps deliver essential hydration to delicate skin. Rosehip, Sesame and Jojoba Oils help promote increased moisture levels, leaving skin feeling soothed and nourished.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Sukin_Sensitive_Facial_Moisturizer.png?v=1640469776",
        ingredients: [
          "water (aqua)",
          "aloe barbadensis leaf juice",
          "sesamum indicum (sesame) seed oil",
          "cetearyl alcohol",
          "glycerin",
          "cetyl alcohol",
          "ceteareth-20",
          "rosa canina fruit oil (rosehip)",
          "theobroma cacao (cocoa) seed butter",
          "butyrospermum parkii (shea) butter",
          "simmondsia chinensis (jojoba) seed oil",
          "persea gratissima (avocado) oil",
          "triticum vulgare (wheat) germ oil",
          "tocopherol (vitamin e)",
          "cucumis sativus (cucumber) fruit extract",
          "chamomilla recutita (matricaria) flower extract (chamomile)",
          "vanillin",
          "vanilla planifolia fruit extract",
          "phenoxyethanol",
          "benzyl alcohol",
        ],
        texture: "lotion",
        price_range: "$",
        skin_type: ["oily", "combination", "sensitive"],
        has_fragrance: true,
        has_alcohol: false,
        category: "moisturizer",
        is_clean: true,
        buy_link:
          "https://shop.shoppersdrugmart.ca/Shop/Categories/Beauty/Skin-Care/Face-Moisturizers/Moisturizers/Sensitive-Facial-Moisturizer/p/U572?variantCode=9327693002175",
      },
      {
        routine_step: "Remove",
        name: "Sukin Micellar Cleansing Water",
        description:
          "Our Micellar Cleansing Water is infused with gentle Aloe Vera to thoroughly remove makeup and dirt build up, whilst soothing and purifying the complexion. A refreshing blend of Chamomile and Cucumber calms, leaving skin lightly hydrated and clean.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Sukin_Micellar_Cleansing_Water.png?v=1640469152",
        ingredients: [
          "water (aqua)",
          "aloe barbadensis leaf juice",
          "glycerin",
          "decyl glucoside",
          "lecithin",
          "cucumis sativus (cucumber) fruit extract",
          "chamomilla recutita (matricaria) flower extract (chamomile)",
          "vanillin",
          "alcohol denat.",
          "phenoxyethanol",
          "benzyl alcohol",
        ],
        texture: "water",
        price_range: "$",
        skin_type: ["oily", "normal"],
        has_fragrance: true,
        has_alcohol: true,
        category: "makeup_remover",
        is_clean: true,
        buy_link:
          "https://shop.shoppersdrugmart.ca/Shop/Sukin/Categories/Beauty/Makeup/Face/Makeup-Remover/Micellar-Cleansing-Water/p/U567?variantCode=9327693004391#",
      },
      {
        routine_step: "Cleanse",
        name: "Youth To The People Superfood Antioxidant Cleanser",
        description:
          "An award-winning face wash with cold-pressed antioxidants to remove makeup, prevent buildup in pores, and support skin’s pH balance.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Youth_To_The_People_Superfood_Antioxidant_Cleanser.png?v=1640467532",
        ingredients: [
          "water/aqua/eau",
          "cocamidopropyl hydroxysultaine",
          "sodium cocoyl glutamate",
          "aloe barbadensis (aloe vera) leaf juice",
          "sorbeth-230 tetraoleate",
          "polysorbate 20",
          "brassica oleracea acephala (kale) extract",
          "spinacia oleracea (spinach) leaf extract",
          "camellia sinensis (green tea) leaf extract",
          "medicago sativa (alfalfa) extract",
          "chamomilla recutita (matricaria) flower extract",
          "tetrahexyldecyl ascorbate (vitamin c)",
          "glycerin",
          "panthenol (vitamin b5)",
          "tocopheryl acetate (vitamin e)",
          "decyl glucoside",
          "sorbitan laurate",
          "tetrasodium glutamate diacetate",
          "gluconolactone",
          "calcium gluconate",
          "ethylhexylglycerin",
          "maltodextrin",
          "citric acid",
          "phenoxyethanol",
          "potassium sorbate",
          "sodium benzoate",
          "chlorophyllin-copper complex (ci 75810)",
          "gardenia jasminoides (jasmine) fruit extract",
          "fragrance/parfum",
        ],
        texture: "gel",
        price_range: "$$$",
        skin_type: ["normal", "dry", "combination", "oily"],
        has_fragrance: true,
        has_alcohol: false,
        category: "cleanser",
        is_clean: true,
        buy_link:
          "https://www.sephora.com/ca/en/product/kale-spinach-green-tea-age-prevention-cleanser-P411387?skuId=1863588&icid2=skugrid:p411387:product",
      },
      {
        routine_step: "Hydrate & Protect",
        name: "Olay Complete Lotion Moisturizer with SPF 30 Sensitive",
        description:
          "Gentle with zinc oxide provides sun protection & long-lasting hydration for sensitive skin. Daily SPF moisturizer helps prevent premature skin damage with Broad Spectrum SPF 30 UVA/UVB Sunscreen. Conditions skin surface with Vitamin E & aloe to maintain healthy-looking skin. Oil-free, fragrance-free, non-greasy, dermatologically tested & non-comedogenic (won’t clog pores) formula for sensitive skin types. Nourishes 7 layers deep into skin’s surface to help protect beautiful, younger-looking skin.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Olay_Complete_Lotion_Moisturizer_with_SPF_30_Sensitive.png?v=1640478139",
        ingredients: [
          "octinoxate (7.5%)",
          "zinc oxide (7.0%)",
          "octisalate (2.5%)",
          "octocrylene (2.6%)",
          "water",
          "isohexadecane",
          "glycerin",
          "steareth-21",
          "cyclopentasiloxane",
          "polyacrylamide",
          "stearyl alcohol",
          "polymethylsilsesquioxane",
          "polyethylene",
          "panthenol",
          "niacinamide",
          "c13-14 isoparaffin",
          "behenyl alcohol",
          "dmdm hydantoin",
          "tocopheryl acetate",
          "cetyl alcohol",
          "triethoxycaprylylsilane",
          "peg/ppg-20/20 dimethicone",
          "laureth-7",
          "steareth-2",
          "oleth-3 phosphate",
          "disodium edta",
          "iodopropynyl butylcarbamate",
          "aloe barbadensis leaf extract",
          "camellia sinensis leaf extract",
        ],
        texture: "lotion",
        price_range: "$",
        skin_type: ["sensitive"],
        has_fragrance: false,
        has_alcohol: false,
        is_waterproof: false,
        spf: 30,
        sunscreen_type: ["chemical", "physical"],
        category: "moisturizer",
        buy_link:
          "https://www.walmart.ca/en/ip/olay-complete-lotion-moisturizer-with-spf-30-sensitive/6000033098996?skuId=10066484&offerId=10066484&utm_medium=paid_search&utm_source=google&utm_campaign=always_on&cmpid=SEM_CA_77_Y55KYL6JHR_71700000053641833_58700006637388428&utm_id=SEM_CA_77_Y55KYL6JHR_71700000053641833_58700006637388428&gclsrc=aw.ds&&gclid=CjwKCAiAn5uOBhADEiwA_pZwcKtxZ7O7YBmyS1zC3FZuuUraP_8a06Ng9jpPDFETyzdL1oCF0lOP2xoCZy4QAvD_BwE&gclsrc=aw.ds",
      },
      {
        routine_step: "Hydrate & Protect",
        name: "CeraVe AM Facial Moisturizing Lotion SPF 30",
        description:
          "Developed with dermatologists, CeraVe Facial Moisturizing Lotion SPF 30 provides UV protection while helping to restore the natural skin protective barrier. This lightweight, non-greasy lotion, with 3 essential ceramides and hyaluronic acid, provides all day hydration after just one use.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/CeraVe_AM_Facial_Moisturizing_Lotion_SPF_30.png?v=1640479027",
        ingredients: [
          "homosalate (10%)",
          "menthyl anthranilate (meradimate) (5%)",
          "octinoxate (ethylhexyl",
          "methoxycinnamate) (5%)",
          "octocrylene (2%)",
          "zinc oxide (6.3%)",
          "non-medicinal ingredients: water",
          "aluminum starch octenylsuccinate",
          "behentrimonium methosulphate",
          "cetearyl alcohol",
          "carbomer",
          "ceramide ap ",
          "ceramide np",
          "ceramide eop",
          "cholesterol",
          "dimethicone",
          "disodium edta",
          "glycerin",
          "hydroxyethylcellulose",
          "methylparaben",
          "niacinamide",
          "propylparaben",
          "phytosphingosine",
          "sodium hyaluronate",
          "sodium lauroyl lactylate",
          "xanthan gum",
        ],
        texture: "lotion",
        price_range: "$",
        skin_type: ["all", "sensitive"],
        has_fragrance: false,
        has_alcohol: false,
        is_waterproof: false,
        spf: 30,
        sunscreen_type: ["chemical", "physical"],
        category: "moisturizer",
        buy_link:
          "https://www.walmart.ca/en/ip/cerave-daily-facial-moisturizing-lotion-spf-30-with-hyaluronic-acid-and-niacinamide-fragrance-free-face-moisturizer/6000200706121",
      },
      {
        routine_step: "Hydrate & Protect",
        name: "Neutrogena Moisture Oil-Free Moisturizer SPF 30",
        description:
          "NEUTROGENA MOISTURE® Oil Free SPF 30 is a lightweight, non-greasy formula that is clinically proven to provide long-lasting moisturization for softer, smoother, younger-looking skin.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Neutrogena_Moisture_Oil-Free_Moisturizer_SPF_30.png?v=1640481021",
        ingredients: [
          "homosalate (12%)",
          "oxybenzone (6%)",
          "octisalate (5%)",
          "avobenzone (3%)",
          "octocrylene (2.35%)",
          "behenyl alcohol",
          "benzyl alcohol",
          "bht",
          "caprylyl methicone",
          "cetearyl alcohol",
          "cetearyl glucoside",
          "diethylhexyl 2,6-naphthalate",
          "dimethicone",
          "disodium edta",
          "ethylhexylglycerin",
          "glycerin",
          "glyceryl stearate",
          "hydrogenated palm glycerides",
          "methylisothiazolinone",
          "methylparaben",
          "peg-100 stearate",
          "potassium cetyl phosphate",
          "propylparaben",
          "styrene/acrylates copolymer",
          "trisiloxane",
          "water (eau)",
          "xanthan gum",
        ],
        texture: "lotion",
        price_range: "$",
        skin_type: ["oily", "combination", "normal", "dry", "acne-prone"],
        has_fragrance: false,
        has_alcohol: false,
        is_waterproof: false,
        spf: 30,
        sunscreen_type: ["chemical"],
        category: "moisturizer",
        buy_link:
          "https://www.walmart.ca/en/ip/neutrogena-moisture-oil-free-moisturizer-spf-30/48122",
      },
      {
        routine_step: "Treat",
        name: "Paula's Choice CLEAR Regular Strength Daily Skin Clearing Treatment with 2.5% Benzoyl Peroxide",
        description:
          "An effective acne treatment that works immediately to fight acne, prevent future breakouts, and reduce redness.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Paula_s_Choice_CLEAR_Regular_Strength_Daily_Skin_Clearing_Treatment_with_2.5_Benzoyl_Peroxide.png?v=1640677260",
        ingredients: [
          "benzoyl peroxide (2.5%)",
          "water (aqua)",
          "propylene glycol (hydration/penetration enhancer)",
          "bisabolol (skin-soothing)",
          "allantoin (skin-soothing)",
          "acrylates/c10-30 alkyl acrylate crosspolymer (texture-enhancing)",
          "hydroxyethylcellulose (texture-enhancing)",
          "sodium citrate (ph adjuster)",
          "laureth-4 (stabilizer)",
          "caprylyl glycol (preservatives)",
          "hexylene glycol (preservatives)",
          "sodium hydroxide (ph adjuster)",
          "disodium edta (stabilizer)",
          "phenoxyethanol (preservative)",
        ],
        price_range: "$",
        has_fragrance: false,
        has_alcohol: false,
        category: "treatment",
        skin_concerns: ["acne"],
        buy_link:
          "https://www.paulaschoice.com/clear-regular-strength-daily-skin-clearing-treatment-with-2.5pct-benzoyl-peroxide/610-6100.html",
      },
      {
        routine_step: "Treat",
        name: "Paula's Choice SKIN PERFECTING 2% BHA Liquid Exfoliant",
        description:
          "Our #1 product worldwide + cult favorite, this gentle leave-on exfoliant with salicylic acid quickly unclogs pores, smooths wrinkles, brightens and evens out skin tone.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Paula_s_Choice_SKIN_PERFECTING_2_BHA_Liquid_Exfoliant.png?v=1640677819",
        ingredients: [
          "water (aqua)",
          "methylpropanediol (hydration)",
          "butylene glycol (hydration)",
          "salicylic acid (beta hydroxy acid/exfoliant)",
          "polysorbate 20 (stabilizer)",
          "camellia oleifera leaf extract (green tea/skin calming/antioxidant)",
          "sodium hydroxide (ph balancer)",
          "tetrasodium edta (stabilizer)",
        ],
        price_range: "$$",
        has_fragrance: false,
        has_alcohol: false,
        category: "treatment",
        skin_concerns: ["blackheads & large pores", "acne"],
        buy_link:
          "https://www.paulaschoice.com/skin-perfecting-2pct-bha-liquid-exfoliant/201-2010.html",
      },
      {
        routine_step: "Treat",
        name: "The Ordinary Alpha Arbutin 2% + HA Hyperpigmentation Serum",
        description:
          "A concentrated serum with pure alpha arbutin and hyaluronic acid for more visibly even-toned skin..",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/The_Ordinary_Alpha_Arbutin_2_HA_Hyperpigmentation_Serum.png?v=1640679414",
        ingredients: [
          "water",
          "alpha-arbutin",
          "polyacrylate crosspolymer-6",
          "hydrolyzed sodium hyaluronate",
          "propanediol",
          "ppg-26-buteth-26",
          "peg-40 hydrogenated castor oil",
          "lactic acid",
          "trisodium ethylenediamine disuccinate",
          "ethoxydiglycol",
          "phenoxyethanol",
          "chlorphenesin",
        ],
        price_range: "$",
        has_fragrance: false,
        has_alcohol: false,
        category: "treatment",
        skin_concerns: ["dark spots & hyperpigmentation"],
        buy_link:
          "https://www.sephora.com/ca/en/product/the-ordinary-deciem-alpha-arbutin-2-ha-P427412?skuId=2031441",
      },
      {
        routine_step: "Treat",
        name: "The Ordinary Retinol 1% in Squalane",
        description:
          "A highly stable, water-free solution of one percent pure retinol.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/The_Ordinary_Retinol_1_in_Squalane.png?v=1640679319",
        ingredients: [
          "squalane",
          "caprylic/capric triglyceride",
          "retinol",
          "solanum lycopersicum (tomato) fruit extract",
          "simmondsia chinensis (jojoba) seed oil",
          "bht",
        ],
        price_range: "$",
        has_fragrance: false,
        has_alcohol: false,
        category: "treatment",
        skin_concerns: ["aging"],
        buy_link:
          "https://www.sephora.com/ca/en/product/retinol-1-in-squalane-P444617?skuId=2238624",
      },
      {
        routine_step: "Treat",
        name: "The Ordinary Buffet Anti-Aging Serum",
        description:
          "A multi-peptide, lightweight, water-based serum that targets multiple signs of visible aging at once and is great for those looking for solutions for signs of aging and supporting visibly healthy skin.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/The_Ordinary_Buffet_Anti-Aging_Serum.png?v=1640679211",
        ingredients: [
          "aqua (water)",
          "glycerin",
          "lactococcus ferment lysate",
          "acetyl hexapeptide-8",
          "pentapeptide-18",
          "palmitoyl tripeptide-1",
          "palmitoyl tetrapeptide-7",
          "palmitoyl tripeptide-38",
          "dipeptide diaminobutyroyl benzylamide diacetate",
          "acetylarginyltryptophyl diphenylglycine",
          "sodium hyaluronate crosspolymer",
          "sodium hyaluronate",
          "allantoin",
          "glycine",
          "alanine",
          "serine",
          "valine",
          "isoleucine",
          "proline",
          "threonine",
          "histidine",
          "phenylalanine",
          "arginine",
          "aspartic acid",
          "trehalose",
          "fructose",
          "glucose",
          "maltose",
          "urea",
          "sodium pca",
          "pca",
          "sodium lactate",
          "citric acid",
          "hydroxypropyl cyclodextrin",
          "sodium chloride",
          "sodium hydroxide",
          "butylene glycol",
          "pentylene glycol",
          "acacia senegal gum",
          "xanthan gum",
          "carbomer",
          "polysorbate 20",
          "ppg-26-buteth-26",
          "peg-40 hydrogenated castor oil",
          "trisodium ethylenediamine disuccinate",
          "ethoxydiglycol",
          "sodium benzoate",
          "caprylyl glycol",
          "ethylhexylglycerin",
          "phenoxyethanol",
          "chlorphenesin",
        ],
        price_range: "$",
        has_fragrance: false,
        has_alcohol: false,
        category: "treatment",
        skin_concerns: ["aging"],
        buy_link:
          "https://www.sephora.com/ca/en/product/the-ordinary-deciem-buffet-P427420",
      },
      {
        routine_step: "Treat",
        name: "The Ordinary Salicylic Acid 2% Anhydrous Solution Pore Clearing Serum",
        description:
          "A water-free serum formulated with salicylic acid to effectively decongest the skin and provide surface exfoliation.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/The_Ordinary_Salicylic_Acid_2_Anhydrous_Solution_Pore_Clearing_Serum.png?v=1640679706",
        ingredients: [
          "squalane",
          "caprylic/capric triglyceride",
          "pentylene glycol",
          "salicylic acid",
          "oleic/linoleic/linolenic polyglycerides",
          "4-t-butylcyclohexanol",
          "hydroxymethoxyphenyl decanone",
          "phenoxyethanol",
          "chlorphenesin",
        ],
        price_range: "$",
        has_fragrance: false,
        has_alcohol: false,
        category: "treatment",
        skin_concerns: ["blackheads & large pores", "acne"],
        buy_link:
          "https://www.sephora.com/ca/en/product/the-ordinary-salicylic-acid-2-anhydrous-solution-pore-clearing-serum-P479732?skuId=2495687",
      },
      {
        routine_step: "Treat",
        name: "The Ordinary Hyaluronic Acid 2% + B5 Hydrating Serum",
        description:
          "A hydrating formula with ultra-pure, vegan hyaluronic acid.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/The_Ordinary_Hyaluronic_Acid_2_B5_Hydrating_Serum.png?v=1640680540",
        ingredients: [
          "water",
          "sodium hyaluronate",
          "pentylene glycol",
          "propanediol",
          "sodium hyaluronate crosspolymer",
          "panthenol",
          "ahnfeltia concinna extract",
          "glycerin",
          "trisodium ethylenediamine disuccinate",
          "citric acid",
          "isoceteth-20",
          "ethoxydiglycol",
          "ethylhexylglycerin",
          "hexylene glycol",
          "1,2-hexanediol",
          "phenoxyethanol",
          "caprylyl glycol",
        ],
        price_range: "$",
        has_fragrance: false,
        has_alcohol: false,
        category: "treatment",
        skin_concerns: ["dryness"],
        buy_link:
          "https://www.sephora.com/ca/en/product/the-ordinary-deciem-hyaluronic-acid-2-b5-P427419?skuId=2031375",
      },
      {
        routine_step: "Treat",
        name: "Stridex Medicated Acne Pads, Maximum Strength",
        description:
          "Stridex Maximum Pads have the highest level of acne-fighting medicine allowed in a non-prescription formula (2% salicylic acid) and are recommended for cases of moderate acne. Max Pads have effective skin cleansers that work to remove dirt, oil, and sweat from the surface of the skin. The medication penetrates to unclog pores and dissolve deep-down oil. They even remove what soaps and face washes leave behind! Completely alcohol-free for acne-fighting effectiveness without the burn. Continues working between uses.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Stridex_Medicated_Acne_Pads_Maximum_Strength.png?v=1640681203",
        ingredients: [
          "salicylic acid (2%)",
          "ammonium lauryl sulfate",
          "ammonium xylenesulfonate",
          "citric acid",
          "dmdm hydantoin",
          "fragrance",
          "menthol",
          "ppg-5-ceteth-20",
          "purified water",
          "simethicone",
          "sodium borate",
          "tetrasodium edta",
        ],
        price_range: "$",
        has_fragrance: true,
        has_alcohol: false,
        category: "treatment",
        skin_concerns: ["blackheads & large pores", "acne"],
        buy_link:
          "https://ca.iherb.com/pr/stridex-single-step-acne-control-maximum-alcohol-free-90-soft-touch-pads/44105",
      },
      {
        routine_step: "Treat",
        name: "SkinCeuticals C E Ferulic",
        description: `CE Ferulic is a revolutionary antioxidant combination that delivers advanced environmental protection against photoaging by neutralizing free radicals that cause accelerated signs of aging. Provides advanced environmental protection against damaging free radicals induced by UVA, UVB, and infrared radiation. Increases firmness and replenishes lipids to visibly reduce wrinkles. Once absorbed, this serum can‚'t be washed or rubbed off- It remains effective for a minimum of 72 hours, making it an excellent addition to sunscreen.`,
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/635494363708_C_E_FERULIC_BIL.png?v=1640722351",
        ingredients: [
          "water",
          "ethoxydiglycol",
          "ascorbic acid",
          "glycerin",
          "propylene glycol",
          "laureth-23",
          "phenoxyethanol",
          "tocopherol",
          "triethanolamine",
          "ferulic acid",
          "panthenol",
          "sodium hyaluronate",
        ],
        price_range: "$$$",
        has_fragrance: false,
        has_alcohol: false,
        category: "treatment",
        skin_concerns: ["dark spots & hyperpigmentation", "aging"],
        buy_link:
          "https://www.skinceuticals.ca/en/skin-care/ce-ferulic-635494363708.html?gclid=CjwKCAiAiKuOBhBQEiwAId_sK8mc3xUnsJYOKuKGOxOE9CrFv-bUxd2rCfxhtYP7u-rDbavvGzp4eRoC1sYQAvD_BwE&gclsrc=aw.ds",
      },
      {
        routine_step: "Tone",
        name: "I'm From Rice Toner",
        description:
          "I'm From Rice Toner contains the best rice grown in Yeoju where is the origin of the rice. The immaculate rice called 'GOA RICE' delivers clean and clear skin and makes skin smooth so that skin is glowing from the inside of the skin. Experience the balanced skin with rice that is the most familiar and extraordinary ingredient from the nature in Korea.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/I_m_From_Rice_Toner.png?v=1640722898",
        ingredients: [
          "oryza sativa (rice) extract (77.78%)",
          "methylpropanediol",
          "triethylhexanoin",
          "hydrogenated poly (c6-14 olefin)",
          "niacinamide",
          "pentylene glycol",
          "portulaca oleracea extract",
          "oryza sativa (rice) bran extract (0.1%)",
          "ulmus davidiana root extract",
          "amaranthus caudatus seed extract",
          "hydrogenated lecithin",
          "water",
          "polyglyceryl-10 myristate",
          "butylene glycol",
          "adenosine",
          "cellulose gum",
          "ethylhexylglycerin",
          "1,2-hexanediol",
        ],
        price_range: "$$",
        skin_type: ["all"],
        has_fragrance: false,
        has_alcohol: false,
        category: "toner",
        buy_link:
          "https://ca.iherb.com/pr/i-m-from-rice-toner-5-07-fl-oz-150-ml/90196",
      },
      {
        routine_step: "Tone",
        name: "Pyunkang Yul Acne Toner",
        description:
          "Acne Toner is a toner that has a refreshing feeling that helps sebum control and convergence.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Pyunkang_Yul_Acne_Toner.png?v=1640723329",
        ingredients: [
          "water",
          "butylene glycol",
          "dimethyl sulfone",
          "pyridoxine hci",
          "salix alba (willow) bark extract",
          "niacinamide",
          "forsythia suspensa fruit extract",
          "centella asiatica extract",
          "polygonum cuspidatum root extract",
          "scutellaria baicalensis root extract",
          "camellia sinensis leaf extract",
          "glycyrrhiza uralensis (licorice) root extract",
          "chamomilla recutita (matricaria) flower extract",
          "rosmarinus officinalis (rosemary) leaf extract",
          "copper tripeptide-1",
          "glycerin",
          "hydroxyacetophenone",
          "myrtus communis extract",
          "tropaeolum majus  extract",
          "ethylhexylglycerin",
          "disodium edta",
        ],
        price_range: "$",
        skin_type: ["acne-prone"],
        has_fragrance: false,
        has_alcohol: false,
        category: "toner",
        buy_link:
          "https://ca.iherb.com/pr/pyunkang-yul-acne-toner-5-07-fl-oz-150-ml/85114",
      },
      {
        routine_step: "Tone",
        name: "Yes To Calming Toner Cucumbers",
        description:
          "Refreshing, alcohol-free toner gently cleanses, removing residual oils, dirt and makeup without stripping the skin. Enriched with cucumber extract, witch hazel and aloe vera to help balance, tone, hydrate, nourish and calm sensitive skin.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Yes_To_Calming_Toner_Cucumbers.png?v=1640723873",
        ingredients: [
          "water",
          "glycerin",
          "hamamelis virginiana (witch hazel) leaf extract",
          "cucumis sativus (cucumber) fruit extract",
          "aloe barbadensis leaf juice powder",
          "maltodextrin",
          "citric acid",
          "sodium benzoate",
          "potassium sorbate",
          "phenoxyethanol",
          "ethylhexylglycerin",
          "fragrance",
        ],
        price_range: "$",
        skin_type: ["all"],
        has_fragrance: true,
        has_alcohol: false,
        category: "toner",
        buy_link:
          "https://ca.iherb.com/pr/yes-to-calming-toner-cucumbers-12-fl-oz-355-ml/109767",
      },
      {
        routine_step: "Tone",
        name: "Thayers Alcohol-Free Rose Petal Witch Hazel Facial Toner",
        description:
          "Flower Power. Make your skin bloom with THAYERS Rose Petal Facial Mist. This pH balanced, gentle toner is derived from a time-honored formula, developed by Thayers to cleanse, tone, and moisturize skin. Formulated with Rose Water and Thayers unique, proprietary blend of Aloe Vera and non-distilled Witch Hazel that is grown exclusively for Thayers on a family farm. By avoiding distillation of their Witch Hazel, we’re able to preserve the naturally-occurring, beneficial tannins which are known to their antioxidant benefits. The Thayers toner formula imparts a natural glow to your skin. Thayers elixirs have been a fixture in medicine cabinets for generations – once you use them you’ll know why.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Thayers_Alcohol-Free_Rose_Petal_Witch_Hazel_Facial_Toner.png?v=1640724348",
        ingredients: [
          "aqua/water/eau",
          "glycerin",
          "hamamelis virginiana (witch hazel) bark/leaf/twig extract",
          "aloe barbadensis leaf extract",
          "rosa centifolia flower water",
          "parfum/fragrance",
          "phenoxyethanol",
          "caprylyl glycol",
          "ethylhexylglycerin",
          "citric acid",
          "potassium hydroxide",
          "hamamelis virginiana (witch hazel) bark/leaf/twig extract and aloe barbadensis leaf",
        ],
        price_range: "$",
        skin_type: ["all"],
        has_fragrance: true,
        has_alcohol: false,
        category: "toner",
        buy_link:
          "https://well.ca/products/thayers-alcohol-free-rose-petal_11170.html",
      },
      {
        routine_step: "Tone",
        name: "Thayers Facial Toner with Witch Hazel Unscented",
        description:
          "Thayers Alcohol-Free Unscented Witch Hazel with Organic Aloe Vera Formula Facial Toner has all the replenishing, revitalizing magic of our scented varieties, but is undetectable by the nose.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Thayers_Facial_Toner_with_Witch_Hazel_Unscented.png?v=1640724663",
        ingredients: [
          "purified water",
          "glycerin",
          "certified organic witch hazel ext blend (hamamelis virginiana extract (witch hazel*)",
          "aloe barbadensis leaf juice (filet of aloe vera*))",
          "phenoxyethanol",
          "citric acid",
          "citrus grandis (grapefruit) seed extract",
        ],
        price_range: "$",
        skin_type: ["all"],
        has_fragrance: false,
        has_alcohol: false,
        category: "toner",
        buy_link:
          "https://well.ca/products/thayers-facial-toner-with-witch-hazel-unscented_11172.html",
      },
      {
        routine_step: "Hydrate & Protect",
        name: "Fenty Skin Hydra Vizor Invisible Moisturizer Broad Spectrum SPF 30",
        description:
          "A refillable two-in-one sunscreen moisturizer that’s lightweight, oil free, noncomedogenic, and invisible—it targets dark spots, and is makeup-friendly.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Fenty_Skin_Hydra_Vizor_Invisible_Moisturizer_Broad_Spectrum_SPF_30.png?v=1640758833",
        ingredients: [
          "avobenzone (3%)",
          "homosalate (9%)",
          "octisalate (4.5%)",
          "aqua/water/eau",
          "glycerin",
          "carthamus tinctorius oleosomes",
          "pentylene glycol",
          "butylene glycol",
          "c12-15 alkyl benzoate",
          "niacinamide",
          "zea mays (corn) starch",
          "fragrance/parfum",
          "sodium acrylate/sodium acryloyldimethyl taurate copolymer",
          "phenoxyethanol",
          "isohexadecane",
          "dimethicone",
          "ethylhexyl methoxycrylene",
          "polysorbate 80",
          "dl-alpha tocopheryl acetate",
          "aloe barbadensis leaf juice",
          "acrylates/c10-30 alkyl acrylate crosspolymer",
          "sorbitan oleate",
          "ethylhexylglycerin",
          "gluconolactone",
          "trisodium ethylenediamine disuccinate",
          "sodium hydroxide",
          "xanthan gum",
          "citric acid",
          "potassium hydroxide",
          "sodium benzoate",
          "barosma betulina leaf extract",
          "citrullus lanatus (watermelon) seed extract",
          "adansonia digitata pulp extract",
          "hyaluronic acid",
          "sodium hyaluronate",
          "red 33 (ci 17200)",
          "potassium sorbate",
          "d-alpha tocopherol",
          "benzyl salicylate",
          "citral",
          "hexyl cinnamal",
          "limonene",
          "linalool",
        ],
        texture: "lotion",
        price_range: "$$$",
        skin_type: ["normal", "oily", "dry", "combination"],
        has_fragrance: true,
        spf: 50,
        is_waterproof: false,
        sunscreen_type: ["chemical"],
        category: "moisturizer",
        has_alcohol: false,
        buy_link:
          "https://www.sephora.com/ca/en/product/fenty-skin-hydra-vizor-invisible-moisturizer-broad-spectrum-spf-30-P467023?skuId=2418960",
      },
      {
        routine_step: "Hydrate & Protect",
        name: "Neutrogena Hydro Boost Gel Cream SPF 25",
        description:
          "A lightweight water gel formula is oil free and non-comedogenic and moisturizes to help revitalize the look of dull, tired skin. This moisturizer also provides broad spectrum UVA/UVB protection. Boost moisture with a complex of purified hyaluronic acid.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Neutrogena_Hydro_Boost_Gel_Cream_SPF_25.png?v=1640767757",
        ingredients: [
          "homosalate (4%)",
          "octisalate (4%)",
          "avobenzone (2%)",
          "octocrylene (2%)",
          "blue 1",
          "caprylyl methicone",
          "chlorphenesin",
          "disodium edta",
          "ethylhexylglycerin",
          "glycerin",
          "glyceryl stearate",
          "methyl methacrylate crosspolymer",
          "parfum",
          "pentylene glycol",
          "phenoxyethanol",
          "red 40",
          "sodium acryloyldimethyltaurate/vp crosspolymer",
          "sodium hyaluronate",
          "sodium hydroxide",
          "tocopheryl acetate",
          "water",
        ],
        texture: "gel-cream",
        price_range: "$",
        skin_type: ["normal", "oily", "dry", "combination"],
        has_fragrance: true,
        spf: 25,
        is_waterproof: false,
        sunscreen_type: ["chemical"],
        category: "moisturizer",
        has_alcohol: false,
        buy_link:
          "https://www.walmart.ca/en/ip/neutrogena-hydro-boost-gel-face-cream-spf-25-with-broad-spectrum-uvauvb-hydrating-hyaluronic-acid-antioxidants-oil-free-moisturizer-non-comedogenic-47/6000200713157",
      },
      {
        routine_step: "Treat",
        name: "Pixi Beauty Retinol Tonic",
        description:
          "A youth-preserving toner for hydrated, fresh looking skin. Turn back time with this rejuvenating skin toner. The miracle formula is packed with powerful antioxidants and botanicals (such as jasmine flower) to recondition the skin and permeate each and every pore. Rebuilding damaged moisture barriers and locking-in moisture, the silky soft toner works even in minimal doses. Smoother, softer skin in no time!",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Pixi_Beauty_Retinol_Tonic.png?v=1640769105",
        ingredients: [
          "water",
          "rosemarinus officinalis (rosemary) leaf water",
          "glycerin",
          "propanediol",
          "peg-40 hydrogenated castor oil",
          "methyl gluceth-20",
          "caprylic/capric triglyceride",
          "peg-8",
          "panthenol",
          "magnesium ascorbyl phosphate",
          "sodium hyaluronate",
          "lecithin",
          "polysorbate 20",
          "oenothera biennis (evening primrose) flower extract",
          "hibiscus rosa-sinensis flower extract",
          "sodium acrylates copolymer",
          "palmitoyl tripeptide-28",
          "hydroxypropyl cyclodextrin",
          "retinol",
          "phenoxyethanol",
          "jasminum officinale (jasmine) flower/leaf extract",
          "lavandula angustifolia (lavender) flower/leaf/stem extract",
          "eugenia caryophyllus (clove) flower extract",
          "vitis vinifera (grape) fruit extract",
          "sodium citrate",
          "disodium edta",
          "citric acid",
          "ethylhexylglycerin",
        ],
        price_range: "$",
        has_fragrance: true,
        has_alcohol: false,
        category: "treatment",
        skin_concerns: ["aging"],
        buy_link:
          "https://ca.iherb.com/pr/pixi-beauty-retinol-tonic-3-4-fl-oz-100-ml/85643",
      },
      {
        routine_step: "Treat",
        name: "Elizavecca Witch Piggy Hell Pore Control Hyaluronic Acid 97",
        description:
          "A powerful moisturizer for a vibrant skin! Elizavecca Witch Piggy Hell Pore Control Hyaluronic Acid 97% provides moisture to your skin. It features 97% of hyaluronic acid, the substance that exists in human body and it retains moisture from skin's uppermost layers down to its dermis layer. By regulating proper hydration level of pores, it helps solving pore problems and makes your skin glow. With non-sticky formula, it does not leave a greasy feeling.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Elizavecca_Witch_Piggy_Hell_Pore_Control_Hyaluronic_Acid_97.png?v=1640808683",
        ingredients: [
          "water",
          "1,2-hexanediol",
          "niacinamide",
          "sodium hyaluronate (9,700ppm)",
          "propylene glycol",
          "peg-60 hydrogenated castor oil",
          "carbomer",
          "arginine",
          "adenosine",
          "allantoin",
          "fragrance",
        ],
        price_range: "$",
        has_fragrance: true,
        has_alcohol: false,
        category: "treatment",
        skin_concerns: ["dryness"],
        buy_link:
          "https://ca.iherb.com/pr/elizavecca-witch-piggy-hell-pore-control-hyaluronic-acid-97-1-69-fl-oz-50-ml/70016",
      },
      {
        routine_step: "Treat",
        name: "Glow Recipe Plum Plump™ Hyaluronic Acid Serum",
        description:
          "A hydrating serum with juicy plum and five weights of hyaluronic acid that fills skin with hydration for a visibly plump effect.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/Glow_Recipe_Plum_Plump_Hyaluronic_Acid_Serum.png?v=1640808903",
        ingredients: [
          "aqua/water/eau",
          "glycerin",
          "propanediol",
          "pentylene glycol",
          "pleiogynium timoriense fruit extract",
          "podocarpus elatus fruit extract",
          "terminalia ferdinandiana fruit extract",
          "sodium acetylated hyaluronate",
          "sodium hyaluronate",
          "tremella fuciformis polysaccharide",
          "acacia seyal gum extract",
          "sr-spider polypeptide-1",
          "pantothenic acid",
          "phospholipids",
          "sodium hydroxide",
          "spirulina maxima extract",
          "raphanus sativus (radish) root extract",
          "caprylyl glycol",
          "chlorphenesin",
          "tetrasodium glutamate diacetate",
          "polyglyceryl-6 caprylate",
          "polyglyceryl-4 caprate",
          "potassium sorbate",
          "propylene glycol",
          "1,2-hexanediol",
          "citric acid",
          "ethylhexylglycerin",
          "hydroxyacetophenone",
          "carrageenan/chondrus crispus",
          "xanthan gum",
          "phenoxyethanol",
          "fragrance/parfum",
        ],
        price_range: "$$$",
        has_fragrance: true,
        has_alcohol: false,
        category: "treatment",
        skin_concerns: ["dryness"],
        buy_link:
          "https://www.sephora.com/ca/en/product/glow-recipe-plum-plump-hyaluronic-acid-serum-P462699?skuId=2371524",
      },
      {
        routine_step: "Hydrate",
        name: "e.l.f. cosmetics Holy Hydration! Face Cream",
        description:
          "For a powerful boost of hydration to the face and luminous skin, this award-winning facial moisturizer is great for dry skin and does it all. It’s packed with skin-loving ingredients that even out skin tone and replenish lost moisture for a firmed up, bouncy complexion. Great for daytime and nighttime use, the non-greasy face cream quickly sinks into the skin for a smooth, super-soft feel.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/e.l.f._cosmetics_Holy_Hydration_Face_Cream.png?v=1640809945",
        ingredients: [
          "water (aqua)",
          "isohexadecane",
          "stearyl heptanoate",
          "glycerin",
          "butylene glycol",
          "isopropyl isostearate",
          "niacinamide",
          "cetearyl olivate",
          "trehalose",
          "squalane",
          "dimethicone",
          "stearic acid",
          "aluminum starchoctenylsuccinate",
          "polymethylsilsesquioxane",
          "silica",
          "sodium hyaluronate",
          "palmitoyl tripeptide-1",
          "palmitoyl tetrapeptide-7",
          "panthenol (vb5)",
          "sorbitanolivate",
          "cetearyl alcohol",
          "glyceryl stearate",
          "peg-100 stearate",
          "polyethylene",
          "disodium edta",
          "polyacrylate-13",
          "polyisobutene",
          "polysorbate 20",
          "caprylylglycol",
          "phenoxyethanol",
          "ethylhexylglycerin",
          "fragrance (parfum)",
          "carbomer",
        ],
        texture: "cream",
        price_range: "$",
        skin_type: ["all"],
        has_fragrance: true,
        has_alcohol: false,
        category: "moisturizer",
        is_clean: true,
        buy_link:
          "https://well.ca/products/elf-cosmetics-holy-hydration-face-cream_203803.html",
      },
      {
        routine_step: "Hydrate",
        name: "e.l.f. cosmetics Holy Hydration! Face Cream Fragrance Free",
        description:
          "For a powerful boost of hydration to the face and luminous skin, indulge in the fragrance-free version of our award-winning moisturizing face cream. It’s packed with skin-loving ingredients that even out skin tone and replenish lost moisture for a firmed up, bouncy complexion. Great for daytime and nighttime use even on sensitive skin, the non-greasy formula quickly sinks into the skin for a smooth, super-soft feel.",
        img_url:
          "https://cdn.shopify.com/s/files/1/0504/5193/9494/files/e.l.f._cosmetics_Holy_Hydration_Face_Cream_Fragrance_Free.png?v=1640810311",
        ingredients: [
          "water (aqua)",
          "isohexadecane",
          "stearyl heptanoate",
          "glycerin",
          "butylene glycol",
          "isopropyl isostearate",
          "niacinamide",
          "cetearyl olivate",
          "trehalose",
          "squalane",
          "dimethicone",
          "stearic acid",
          "aluminum starch octenylsuccinate",
          "polymethylsilsesquioxane",
          "silica",
          "sodium hyaluronate",
          "palmitoyl tripeptide-1",
          "palmitoyl tetrapeptide-7",
          "panthenol (vb5)",
          "sorbitan olivate",
          "cetearyl alcohol",
          "glyceryl stearate",
          "peg-100 stearate",
          "polyethylene",
          "disodium edta",
          "polyacrylate-13",
          "polyisobutene",
          "polysorbate 20",
          "caprylyl glycol",
          "phenoxyethanol",
          "ethylhexylglycerin",
          "carbomer",
        ],
        texture: "cream",
        price_range: "$",
        skin_type: ["all"],
        has_fragrance: false,
        has_alcohol: false,
        category: "moisturizer",
        is_clean: true,
        buy_link:
          "https://well.ca/products/elf-cosmetics-holy-hydration-face-cream-fragrance-free_203802.html",
      },
    ],
  },
];
