const seeder = require("mongoose-seed");
const dotenv = require("dotenv");

const result = dotenv.config();

if (result.error) {
    // don't proceed if there was an error loading env vars
  throw result.error;
} else {
  seeder.connect(`${process.env.MONGO_URI}`, function () {
    seeder.loadModels(["./models/Product.js"]);
    seeder.clearModels(["Product"], function () {
      // Callback to populate DB once collections have been cleared
      seeder.populateModels(data, function () {
        seeder.disconnect();
      });
    });
  });
}

const data = [
  {
    model: "Product",
    documents: [
      {
        name: "Belif The True Cream Aqua Bomb",
        description: `An ultra-lightweight, gel-cream that instantly cools and refreshes skin while providing intensive hydration. This water-based moisturizer 'floods' the skin with a rush of refreshing hydration and minimizes the appearance of pores for soft, smooth, supple skin. Ideal for normal, combination, and oily skin types.`,
        img_url:
          "https://cdn.shopify.com/s/files/1/0083/4571/4768/products/abomb_2691d2da-cc2c-4a4a-a558-7b1873ae8fe6_1200x.jpg?v=1552511575",
        ingredients: [
          "water",
          "dipropylene glycol",
          "glycerin",
          "methyl trimethicone",
          "alcohol denat",
          "dimethicone",
          "cyclopentasiloxane",
          "1,2-hexanediol",
          "malakite extract",
          "caprylic/capric triglyceride",
          "pentaerythrityl tetraethylhexanoate",
          "peg/ppg/polybutylene glycol-8/5/3 glycerin",
          "alchemilla vulgaris leaf extract",
          "equisetum arvense leaf extract",
          "stellaria media (chickweed) extract",
          "urtica dioica (nettle) leaf extract",
          "plantago lanceolata leaf extract",
          "avena sativa (oat) kernel extract",
          "calendula officinalis flower extract",
          "nepeta cataria extract",
          "rubus idaeus (raspberry) leaf extract",
          "baptisia tinctoria root extract",
          "dimethiconol",
          "polymethylsilsesquioxane",
          "sodium acrylate/acryloyldimethyltaurate/dimethylacrylamide crosspolymer",
          "isohexadecane",
          "polysorbate 60",
          "ceramide 3",
          "cholesterol",
          "butyrospermum parkii (shea) butter",
          "phenl trimethicone",
          "pentaerythrityl tetraisostearate",
          "panthenol",
          "squalane",
          "triethylhexanoin",
          "macadamia ternifolia seed oil",
          "peg-150",
          "peg-40 hydrogenated castor oil",
          "acrylates/c10-30 alkyl acrylate crosspolymer",
          "c14-22 alcohols",
          "arachidyl glucoside",
          "hydrogenated lecithin",
          "peg-100 stearate",
          "stearic acid",
          "glyceryl stearate",
          "carbomer",
          "tromethamine",
          "trisodium edta",
          "fragrance",
          "citronellol",
          "limonene",
          "citral",
          "geraniol",
          "linalool",
        ],
        texture: "gel-cream",
        price_range: "$$",
        skin_type: ["normal", "dry", "combination", "oily"],
        has_fragrance: true,
        category: "moisturizer",
        has_alcohol: true,
      },
      {
        name: "Paula's Choice RESIST Super-Light Wrinkle Defense SPF 30",
        description:
          "A lightly tinted mineral-based formula that protects skin from sun damage and fortifies it with state-of-the-art antioxidants.",
        img_url: "https://i.ebayimg.com/images/g/yXEAAOSwqE1gv5lf/s-l640.jpg",
        ingredients: [
          "zinc oxide (13%)",
          "water",
          "cyclopentasiloxane",
          "peg-12 dimethicone",
          "peg/​ppg-18/​18 dimethicone",
          "lauroyl lysine",
          "sodium chloride",
          "trihydroxystearin",
          "dimethicone crosspolymer",
          "resveratrol",
          "quercetin",
          "epigallocatechin gallate",
          "tocopheryl acetate",
          "tetrahexyldecyl ascorbate",
          "adenosine",
          "bisabolol",
          "salix alba (willow) bark extract",
          "punica granatum (pomegranate) extract",
          "haematococcus pluvialis extract",
          "hydrolyzed corn starch",
          "polysorbate 80",
          "hydrated silica",
          "triethoxycaprylylsilane",
          "c12-15 alkyl benzoate",
          "isopropyl titanium triisostearate",
          "caprylyl glycol",
          "hexylene glycol",
          "ethylhexylglycerin",
          "iron oxide ci77491",
          "iron oxide ci 77492",
          "iron oxide ci 77499",
          "phenoxyethanol",
        ],
        texture: "lotion",
        price_range: "$$",
        skin_type: ["normal", "oily", "combination"],
        has_fragrance: false,
        spf: 50,
        is_waterproof: false,
        sunscreen_type: ["physical"],
        category: "sunscreen",
        has_alcohol: false,
        is_tinted: true,
      },
      {
        name: "Paula's Choice RESIST Skin Restoring Moisturizer with SPF 50",
        description: `This antioxidant-rich moisturizer hydrates and protects with superstar ingredients like niacinamide, shea butter and licorice for flawless, younger-looking skin.`,
        img_url:
          "https://www.beautypedia.com/wp-content/uploads/2017/07/Paulas-Choice-Skincare-RESIST-Skin-Restoring-Moisturizer-SPF-50.jpg",
        ingredients: [
          "avobenzone (3%)",
          "homosalate (5%)",
          "octinoxate (7.50%)",
          "octisalate (5%)",
          "oxybenzone (5%)",
          "water (aqua)",
          "silica",
          "glycerin",
          "cetearyl alcohol",
          "dimethicone",
          "butylene glycol",
          "pentylene glycol",
          "potassium cetyl phosphate",
          "cyclopentasiloxane",
          "pyrus malus (apple) fruit extract",
          "vp/​eicosene copolymer",
          "butyrospermum parkii (shea) butter",
          "allantoin",
          "niacinamide",
          "tocopherol",
          "glycyrrhiza glabra (licorice) root extract",
          "aloe barbadensis leaf juice",
          "atractylodes macrocephala root powder",
          "avena sativa (oat) kernel extract",
          "coffea arabica (coffee) seed extract",
          "portulaca oleracea extract",
          "mahonia aquifolium root extract",
          "diethylhexyl syringylidenemalonate",
          "sarcosine",
          "capryloyl glycine",
          "maltooligosyl glucoside",
          "cetearyl glucoside",
          "dimethiconol",
          "acrylates/​c10-30 alkyl acrylate crosspolymer",
          "hydrogenated starch hydrolysate",
          "hexylene glycol",
          "4-t-butylcyclohexanol",
          "glyceryl stearate",
          "peg-100 stearate",
          "sodium hydroxide",
          "xanthan gum",
          "disodium edta",
          "phenoxyethanol",
          "caprylyl glycol (preservatives)",
          "ethylhexylglycerin",
        ],
        texture: "cream",
        price_range: "$$",
        skin_type: ["normal", "dry"],
        has_fragrance: false,
        spf: 50,
        is_waterproof: false,
        sunscreen_type: ["chemical"],
        category: "moisturizer",
        has_alcohol: false,
      },
      {
        name: "Olay Regenerist Micro-Sculpting Cream Fragrance Free",
        description: `“The Red Jar” – known to many as their go-to, nonnegotiable face moisturizer with over 1 billion jars sold, Olay Micro-Sculpting Fragrance-Free Face Cream is designed to start visibly reducing wrinkles & fine lines starting day 1. Infused with Vitamin B3, Amino-Peptides, Hyaluronic Acid and Antioxidants for ultimate penetration, this moisture-binding moisturizing formula instantly hydrates to visibly firm skin for a lifted look."`,
        img_url:
          "https://i5.walmartimages.ca/images/Large/866/707/6000197866707.jpg",
        ingredients: [
          "water",
          "glycerin",
          "isohexadecane",
          "niacinamide",
          "isopropyl isostearate",
          "aluminum starch octenylsuccinate",
          "nylon-12",
          "dimethicone",
          "panthenol",
          "tocopheryl acetate",
          "palmitoyl pentapeptide-4",
          "sodium peg-7 olive oil carboxylate",
          "sodium hyaluronate",
          "caprylic/capric triglyceride",
          "ceratonia siliqua (carob) fruit extract",
          "stearyl alcohol",
          "polyethylene",
          "cetyl alcohol",
          "behenyl alcohol",
          "sodium acrylates copolymer",
          "titanium dioxide",
          "benzyl alcohol",
          "methylparaben",
          "ethylparaben",
          "dimethiconol",
          "polyacrylamide",
          "peg-100 stearate",
          "propylparaben",
          "cetearyl glucoside",
          "cetearyl alcohol",
          "c13-14 isoparaffin",
          "disodium edta",
          "citric acid",
          "stearic acid",
          "palmitic acid",
          "c12-13 pareth-3",
          "laureth-7",
          "sodium hydroxide",
          "mica",
        ],
        texture: "cream",
        price_range: "$",
        skin_type: ["mature"],
        has_fragrance: false,
        category: "moisturizer",
        has_alcohol: false,
      },
      {
        name: "Tatcha The Water Cream Oil-Free Pore Minimizing Moisturizer",
        description:
          "This lightweight, clarifying water cream releases a burst of hydrating nutrients and pore-refining botanicals for healthy aging and smooth, balanced skin.",
        img_url:
          "https://www.sephora.com/productimages/sku/s1932920-main-zoom.jpg?imwidth=1224",
        ingredients: [
          "water",
          "saccharomyces/camellia sinensis leaf/cladosiphon okamuranus/rice ferment filtrate*",
          "dimethicone",
          "propanediol",
          "glycerin",
          "diglycerin",
          "diphenylsiloxy phenyl trimethicone",
          "gold",
          "belamcanda chinensis root extract",
          "rosa multiflora fruit extract",
          "houttuynia cordata extract",
          "sophora angustifolia root extract",
          "sodium hyaluronate",
          "lecithin",
          "pistacia lentiscus (mastic) gum",
          "sodium chloride",
          "sodium citrate",
          "mica",
          "peg-9 polydimethylsiloxyethyl dimethicone",
          "dimethicone/peg-10/15 crosspolymer",
          "dimethicone/phenyl vinyl dimethicone crosspolymer",
          "disodium edta",
          "tin oxide",
          "titanium dioxide",
          "butylene glycol",
          "ethylhexylglycerin",
          "parfum/fragrance",
          "alcohol",
          "phenoxyethanol",
          "hadasei-3",
        ],
        texture: "gel-cream",
        price_range: "$$$",
        skin_type: ["normal", "oily", "combination"],
        has_fragrance: true,
        category: "moisturizer",
        has_alcohol: true,
      },
      {
        name: "Neutrogena Hydro Boost Facial Gel Cream Extra Dry Skin",
        description:
          "Neutrogena Hydro Boost Gel Cream Extra-Dry instantly quenches dry skin and keeps it looking smooth, supple and hydrated all day. Our unique light-weight formula absorbs quickly, like a gel, but has the long-lasting, intense moisturizing power of a cream, for even extra dry skin. It boosts skin's hydration level and locks it in all day. Formulated with hydrating hyaluronic acid, naturally found in skin, it acts as a sponge for dry skin cells, resulting in more supple and smooth skin.",
        img_url:
          "https://syndi.webcollage.net/asset/456e7f62-1311-478e-af31-ee9ee90a9714/600.jpeg",
        ingredients: [
          "water (eau)",
          "dimethicone",
          "glycerin",
          "cetearyl olivate",
          "polyacrylamide",
          "sorbitan olivate",
          "phenoxyethanol",
          "dimethicone/vinyl dimethicone crosspolymer",
          "synthetic beeswax",
          "c13-14 isoparaf¬fin,dimethicone crosspolymer",
          "dimethiconol",
          "chlorphenesin",
          "carbomer",
          "laureth-7",
          "sodium hyaluronate",
          "ethylhexylglycerin",
          "c12-14 pareth-12",
          "sodium hydroxide",
        ],
        texture: "gel-cream",
        price_range: "$",
        skin_type: ["all"],
        has_fragrance: false,
        category: "moisturizer",
        has_alcohol: false,
      },
      {
        name: "EltaMD UV Daily Broad-Spectrum SPF 40",
        description: `Serious UV protection and superior hydration join forces in this sheer facial sunscreen. EltaMD UV Daily has hyaluronic acid to boost moisture retention and diminish fine lines. This lightweight moisturizer with UV protection can be worn alone or under makeup. Choose from tinted and untinted formulas for use every day.`,
        img_url:
          "https://images-na.ssl-images-amazon.com/images/I/51dNNnbHOHL._AC_SL1296_.jpg",
        ingredients: [
          "zinc oxide (9%)",
          "octinoxate (7.5%)",
          "purified water",
          "petrolatum",
          "isopropyl palmitate",
          "cetearyl glucoside",
          "dimethicone",
          "hydroxyethyl acrylate",
          "sodium acryloyldimethyl taurate copolymer",
          "polisobutene",
          "peg-7 trimethylolpropane coconut ether",
          "sodium hyaluronate",
          "tocopheryl acetate",
          "polyether-1",
          "citric acid",
          "oleth-3 phosphate",
          "phenoxyethanol",
          "butylene glycol",
          "iodopropynyl butylcarbamate",
          "triethoxycaprylylsilane",
        ],
        texture: "lotion",
        price_range: "$$",
        skin_type: ["normal", "combination", "sensitive"],
        has_fragrance: false,
        spf: 40,
        is_waterproof: false,
        sunscreen_type: ["physical", "chemical"],
        category: "moisturizer",
        has_alcohol: false,
      },
      {
        name: "Peter Thomas Roth Water Drench Broad Spectrum SPF 45 Hyaluronic Cloud Moisturizer",
        description:
          "Drench your skin with a liquid cloud of fluffy-light moisture that feels soft and weightless like clouds in the atmosphere, shielding against UVA/UVB rays while helping to keep skin hydrated during sun exposure with a 30% Hyaluronic Acid Complex. Non-greasy, cream-to-water invisible broad-spectrum SPF 45 sunscreen has a 30% complex of Hyaluronic Acid, a potent hydrator that draws in water. Helps plump the look of skin with moisture.",
        img_url:
          "https://m.media-amazon.com/images/I/61BQcFYSVkL._AC_SL1500_.jpg",
        ingredients: [
          "octocrylene (10%)",
          "octisalate (5%)",
          "homosalate (5%)",
          "avobenzone (3%)",
          "water/aqua/eau",
          "polymethylsilsesquioxane",
          "glycerin",
          "dipropylene glycol",
          "dimethicone",
          "argania spinosa kernel oil",
          "dl-alpha tocopheryl acetate",
          "yeast extract",
          "cyclopentasiloxane",
          "cyclohex- asiloxane",
          "phenoxyethanol",
          "lauryl peg-9 polydimethylsiloxyethyl dimethicone,isododecane",
          "dimethicone/peg-10/15 crosspolymer",
          "saccharide isomerate",
          "methyl gluceth-20",
          "sodium chloride",
          "sodium hyaluronate",
          "bisabolol",
          "peg-15/ lauryl dimethicone crosspolymer",
          "sodium pca",
          "propylene glycol",
          "ceteareth-25",
          "sodium benzoate",
          "potassium sorbate",
          "sodium citrate",
          "citric acid",
          "sambucus nigra fruit extract",
          "cetyl alcohol",
          "saccharomyces/magnesium ferment",
          "hydrolyzed silk",
          "behenic acid",
          "ceramide np",
          "cholesterol",
          "ethylhexylglycerin",
          "mica (ci 77019)",
          "deltatocopherol",
          "cera- mide ns",
          "saccharomyces/iron ferment",
          "saccharomyces/copper ferment",
          "saccharomyces/silicon ferment",
          "saccharo- myces/zinc ferment",
          "butylene glycol,ceramide ap",
          "ceramide eop",
          "ceramide eos",
          "olea europaea (olive) leaf extract",
          "caprooyl phytosphingosine",
          "caprooyl sphingosine",
          "disodium edta",
          "ascorbyl palmitate",
        ],
        texture: "gel-cream",
        price_range: "$$$",
        skin_type: ["all"],
        has_fragrance: false,
        spf: 45,
        is_waterproof: true,
        sunscreen_type: ["chemical"],
        category: "moisturizer",
        has_alcohol: false,
      },
      {
        name: "EltaMD UV Clear Broad-Spectrum SPF 46",
        description:
          "Oil-free EltaMD UV Clear helps calm and protect sensitive skin types prone to discoloration and breakouts associated to acne and rosacea. It contains niacinamide (vitamin B3), hyaluronic acid and lactic acid, ingredients that promote the appearance of healthy-looking skin. Very lightweight and silky, it may be worn with makeup or alone. Choose from tinted and untinted formulas for use every day.",
        img_url: "https://m.media-amazon.com/images/I/51bQh8AQbrL._SL1500_.jpg",
        ingredients: [
          "zinc oxide (9%)",
          "octinoxate (7.5%)",
          "purified water",
          "cyclomethicone",
          "niacinamide",
          "octyldodecyl neopentanoate",
          "hydroxyethyl acrylate/sodium acryloyldimethyl taurate copolymer",
          "polyisobutene",
          "peg-7 trimethylolpropane coconut ether",
          "sodium hyaluronate",
          "tocopheryl acetate",
          "lactic acid",
          "oleth-3 phosphate",
          "phenoxyethanol",
          "butylene glycol",
          "iodopropynyl butylcarbamate",
          "triethoxycaprylylsilane",
        ],
        texture: "lotion",
        price_range: "$$",
        skin_type: ["acne-prone", "hyperpigmentation", "rosacea", "sensitive"],
        has_fragrance: false,
        spf: 46,
        is_waterproof: false,
        sunscreen_type: ["physical", "chemical"],
        category: "sunscreen",
        has_alcohol: false,
      },
      {
        name: "Supergoop! Unseen Sunscreen SPF 40 PA+++",
        description:
          "The original, totally invisible, weightless, scentless sunscreen with SPF 40 that leaves a velvety finish. This innovative, antioxidant-rich multitasker has a unique oil-free formula that glides onto skin while providing broad spectrum SPF 40 protection. Use it as a makeup-gripping primer under foundation when you want a little more coverage, or on its own if you want a more natural look. It’s a totally game-changing way to wear sunscreen every day, and it will have you SPF-Obsessed™.",
        img_url:
          "https://www.sephora.com/productimages/sku/s2354207-main-zoom.jpg?imwidth=1224",
        ingredients: [
          "avobenzone (3%)",
          "homosalate (8%)",
          "octisalate (5%)",
          "octocrylene (4%)",
          "isododecane",
          "dimethicone crosspolymer",
          "dimethicone/bis-isobutyl ppg-20 crosspolymer",
          "polymethylsilsesquioxane",
          "isohexadecane",
          "dicaprylyl carbonate",
          "meadowfoam estolide",
          "caprylic/capric triglyceride",
          "polyester-7",
          "neopentyl glycol diheptanoate",
          "lithothamnion calcareum extract",
          "caprylyl glycol",
          "butyrospermum parkii (shea) butter",
          "jojoba esters",
          "mannitol",
          "olibanum",
          "lecithin",
          "microcrystalline cellulose",
          "diatomaceous earth",
          "zinc sulfate",
          "silica",
          "tocopherol",
        ],
        texture: "gel",
        price_range: "$$$",
        skin_type: ["all"],
        has_fragrance: false,
        spf: 40,
        is_waterproof: true,
        sunscreen_type: ["chemical"],
        category: "sunscreen",
        has_alcohol: false,
      },
      {
        name: "Biore UV Aqua Rich Watery Essence SPF 50 PA++++",
        description: `Biore UV Aqua Rich Watery Essence has a light-weight feeling yet it effectively protects from strong UV rays, preventing aging skin and sunburn. This Japanese sunscreen features UV blocking ingredients such as water capsules which when applied to the skin create a pleasant, watery veil. The new formula is enhanced with the so called "Micro Defense" technology which prevents the formation of micro gaps and potential uneven coating. It also contains moisturizing ingredients such as hyaluronic acid, royal jelly and citrus essence to retain moisture.`,
        img_url: "https://m.media-amazon.com/images/I/81mkB+13llL._SL1500_.jpg",
        ingredients: [
          "water",
          "alcohol",
          "ethylhexyl methoxycinnamate",
          "ethylhexyl triazone",
          "isopropyl palmitate",
          "lauryl methacrylate/​sodium methacrylate crosspolymer",
          "diethylamino hydroxybenzoyl hexyl benzoate",
          "hydrogenated polyisobutene",
          "bis-ethylhexyloxyphenol methoxyphenyl triazine",
          "dextrin palmitate",
          "butylene glycol",
          "xylitol",
          "acrylates/​c10-30 alkyl acrylate crosspolymer",
          "dimethicone",
          "c12-15 alkyl benzoate",
          "glycerin",
          "glyceryl stearate",
          "propanediol",
          "glyceryl behenate",
          "vinyl dimethicone/​methicone silsesquioxane crosspolymer",
          "cetyl alcohol",
          "agar",
          "sorbitan distearate",
          "isoceteth-20",
          "polyvinyl alcohol",
          "dimethicone/​vinyl dimethicone crosspolymer",
          "stearoyl glutamic acid",
          "arginine",
          "potassium hydroxide",
          "sodium hydroxide",
          "royal jelly extract",
          "sodium hyaluronate",
          "phenoxyethanol",
          "disodium edta",
          "bht",
          "fragrance",
        ],
        texture: "essence",
        price_range: "$",
        skin_type: ["normal", "oily", "combination"],
        has_fragrance: true,
        spf: 50,
        is_waterproof: true,
        sunscreen_type: ["chemical"],
        category: "sunscreen",
        has_alcohol: true,
      },
      {
        name: "Neutrogena Ultra Gentle Hydrating Cleanser",
        description:
          "Thoroughly cleanse and leave your skin feeling moisturized for naturally soft skin with NEUTROGENA® Ultra Gentle Daily Cleanser, Creamy Formula. This creamy cleanser works in an advanced, skin-friendly way. Uniquely formulated with minimal ingredients, this effective cleanser gently removes excess oil, dirt and makeup. NEUTROGENA® Ultra Gentle Daily Cleanser, Creamy Formula is hypoallergenic, non-comedogenic, fragrance-free, paraben-free, soap-free and dye-free.",
        ingredients: [
          "water",
          "glycerin",
          "cetearyl alcohol",
          "polyglyceryl-10 laurate",
          "phenoxyethanol",
          "cetearyl glucoside",
          "caprylyl glycol",
          "carbomer",
          "sodium hydroxide",
          "ethylhexylglycerin",
        ],
        img_url:
          "https://www.beautypedia.com/wp-content/uploads/2015/03/00376906-73B7-46FE-A01C-A9DC71795CFA_NeutrogenaUltraGentleHydratingCleanserCreamy.jpg",
        texture: "creamy",
        price_range: "$",
        skin_type: ["dry", "sensitive"],
        has_fragrance: false,
        removes_makeup: false,
        category: "cleanser",
      },
      {
        name: "CeraVe Foaming Facial Cleanser",
        description:
          "CeraVe Foaming Facial Cleanser gently removes dirt, excess oil and dead skin cells to reveal a clean, fresh face. The non-irritating formula maintains a healthy moisture balance, never stripping the skin, while eliminating shiny, oily areas. Replenishing hyaluronic acid and ceramides produce a healthy skin barrier so your face feels comfortable without any tightness or dryness.",
        ingredients: [
          "aqua/water/eau",
          "cocamidopropyl hydroxysultaine",
          "glycerin",
          "sodium lauroyl sarcosinate",
          "peg-150 pentaerythrityl tetrastearate",
          "niacinamide",
          "peg-6 caprylic/capric glycerides",
          "sodium methyl cocoyl taurate",
          "propylene glycol",
          "ceramide np",
          "ceramide ap",
          "ceramide eop",
          "carbomer",
          "methylparaben",
          "sodium chloride",
          "sodium lauroyl lactylate",
          "cholesterol",
          "disodium edta",
          "propylparaben",
          "citric acid",
          "tetrasodium edta",
          "hydrolyzed hyaluronic acid",
          "phytosphingosine",
          "xanthan gum",
        ],
        img_url:
          "https://m.media-amazon.com/images/I/51ML6FYmtAL._AC_SL1000_.jpg",
        texture: "foam",
        price_range: "$",
        skin_type: ["normal", "oily"],
        has_fragrance: false,
        removes_makeup: false,
        category: "cleanser",
      },
      {
        name: "COSRX Low pH Good Morning Gel Cleanser",
        description: `A super gentle cleanser that's great for your morning wash this low pH formula gel cleanser doesn't strip your skin of its natural oils and contains purifying botanical ingredients and mild acids to gently cleanse your skin to its most supple and clear texture`,
        img_url:
          "https://i5.walmartimages.com/asr/edb79538-9e68-4b81-9cfd-ab7ba8186e65.7726448daf0a8d6a2ef8f0a568d5a836.png?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
        ingredients: [
          "water",
          "cocamidopropyl betaine",
          "sodium lauroyl methyl isethionate",
          "polysorbate 20",
          "styrax japonicus branch/​fruit/​leaf extract",
          "butylene glycol",
          "saccharomyces ferment",
          "cryptomeria japonica leaf extract",
          "nelumbo nucifera leaf extract",
          "pinus palustris leaf extract",
          "ulmus davidiana root extract",
          "evening primrose flower extract",
          "pueraria lobata root extract",
          "tea tree leaf oil",
          "allantoin",
          "caprylyl glycol",
          "ethylhexylglycerin",
          "betaine salicylate",
          "citric acid",
          "ethyl hexanediol",
          "1,2-hexanediol",
          "trisodium ethylenediamine disuccinate",
          "sodium benzoate",
          "disodium edta",
        ],
        texture: "gel",
        price_range: "$",
        skin_type: ["all"],
        has_fragrance: true,
        removes_makeup: false,
        category: "cleanser",
      },
    ],
  },
];
